### ISSUE TITLE
Inquiry: Is the "Recommended Daily Budget" Definition supported?

### ISSUE THREAD

**Issue by applecrusher** [googleads/googleads-java-lib#102]
Essentially what I am looking for is a way to determine via the API whether a campaign is limited by budget. According to the Google Adwords API, this warning happens when above the recommended daily budget [](https://support.google.com/adwords/answer/2616012?hl=en ). The daily budget is a definition [](https://support.google.com/adwords/answer/25426) , but I don't see where in the API you would get this information. 

I checked the Budget Class in the API but I have had no luck finding what I am looking for. Is this supported? If so, what are the steps to accomplish this goal of finding if a campaign is limited by budget?

**Comment by jradcliff** [comment]
Hi,

Since this question is more about AdWords API functionality (rather than the Java client library), could you please post it to the AdWords API Forum instead?

https://groups.google.com/forum/#!forum/adwords-api

Thanks,
Josh, AdWords API Team
