### ISSUE TITLE
java.lang.NoSuchMethodError: org.apache.commons.configuration.MapConfiguration.<init>(Ljava/util/Properties;)V

### ISSUE THREAD

**Issue by rsiebeling** [googleads/googleads-java-lib#107]
Hi,

I have added the adwords-axis v3.1.1 library and upon calling new OfflineCredentials.Builder().forApi(OfflineCredentials.Api.ADWORDS) I get the given error message : java.lang.NoSuchMethodError: org.apache.commons.configuration.MapConfiguration.<init>(Ljava/util/Properties;)V

Based on earlier answers in the Google AdWords API group it seems to have to do with dependencies but I cannot figure out which one.

The stacktrace and dependencyTree are below,
Richard

**Stacktrace**
java.lang.NoSuchMethodError: org.apache.commons.configuration.MapConfiguration.<init>(Ljava/util/Properties;)V
	at com.google.api.ads.common.lib.conf.ConfigurationHelper.fromSystem(ConfigurationHelper.java:118)
	at com.google.api.ads.common.lib.conf.ConfigurationHelper.createCombinedConfiguration(ConfigurationHelper.java:144)
	at com.google.api.ads.common.lib.conf.ConfigurationProvider.get(ConfigurationProvider.java:67)
	at com.google.api.ads.common.lib.conf.ConfigurationProvider.get(ConfigurationProvider.java:31)
	at com.google.inject.internal.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:40)
	at com.google.inject.internal.SingleParameterInjector.inject(SingleParameterInjector.java:38)
	at com.google.inject.internal.SingleParameterInjector.getAll(SingleParameterInjector.java:62)
	at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:84)
	at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:254)
	at com.google.inject.internal.FactoryProxy.get(FactoryProxy.java:54)
	at com.google.inject.internal.ProviderToInternalFactoryAdapter$1.call(ProviderToInternalFactoryAdapter.java:46)
	at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1031)
	at com.google.inject.internal.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:40)
	at com.google.inject.Scopes$1$1.get(Scopes.java:65)
	at com.google.inject.internal.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:40)
	at com.google.inject.internal.InternalInjectorCreator$1.call(InternalInjectorCreator.java:204)
	at com.google.inject.internal.InternalInjectorCreator$1.call(InternalInjectorCreator.java:198)
	at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1024)
	at com.google.inject.internal.InternalInjectorCreator.loadEagerSingletons(InternalInjectorCreator.java:198)
	at com.google.inject.internal.InternalInjectorCreator.injectDynamically(InternalInjectorCreator.java:179)
	at com.google.inject.internal.InternalInjectorCreator.build(InternalInjectorCreator.java:109)
	at com.google.inject.Guice.createInjector(Guice.java:95)
	at com.google.inject.Guice.createInjector(Guice.java:72)
	at com.google.inject.Guice.createInjector(Guice.java:62)
	at com.google.api.ads.adwords.lib.utils.AdWordsInternals.<clinit>(AdWordsInternals.java:37)
	at com.google.api.ads.common.lib.auth.OfflineCredentials$Api.<clinit>(OfflineCredentials.java:66)
	at anabrix.GoogleAdWordsProcessor.getData(GoogleAdWordsProcessor.scala:41)

**Dependency tree**
[info] Loading project definition from /xxx
[info] Set current project to xxx (in build file:/xxx/)
[info] Updating {file:/xxx/}backend...
[info] Resolving jline#jline;2.12.1 ...
[info] Done updating.
[info] xxx:xxx_2.11:1.0 [S]
[info]   +-com.databricks:spark-csv_2.11:1.3.0 [S]
[info]   | +-com.univocity:univocity-parsers:1.5.1
[info]   | +-org.apache.commons:commons-csv:1.1
[info]   |
[info]   +-com.enragedginger:akka-quartz-scheduler_2.11:1.4.0-akka-2.3.x [S]
[info]   | +-org.quartz-scheduler:quartz:2.2.1
[info]   |   +-c3p0:c3p0:0.9.1.1
[info]   |   +-org.slf4j:slf4j-api:1.6.6 (evicted by: 1.7.7)
[info]   |   +-org.slf4j:slf4j-api:1.7.7
[info]   |
[info]   +-com.fasterxml.jackson.core:jackson-core:2.1.3 (evicted by: 2.6.1)
[info]   +-com.fasterxml.jackson.core:jackson-core:2.6.1
[info]   +-com.github.etaty:rediscala_2.11:1.6.0 [S]
[info]   | +-com.typesafe.akka:akka-actor_2.11:2.3.6 [S]
[info]   | | +-com.typesafe:config:1.2.1
[info]   | |
[info]   | +-org.scala-stm:scala-stm_2.11:0.7 [S]
[info]   |
[info]   +-com.github.nscala-time:nscala-time_2.11:2.10.0 [S]
[info]   | +-joda-time:joda-time:2.9.2
[info]   | +-org.joda:joda-convert:1.2
[info]   |
[info]   +-com.github.t3hnar:scala-bcrypt_2.11:3.0 [S]
[info]   | +-de.svenkubiak:jBCrypt:0.4.1
[info]   |
[info]   +-com.google.api-ads:adwords-axis:3.1.0
[info]   | +-com.google.api-ads:ads-lib-axis:3.1.0
[info]   | | +-com.google.api-ads:ads-lib:3.1.0
[info]   | | | +-com.google.api-client:google-api-client:1.22.0
[info]   | | | | +-com.google.guava:guava-jdk5:17.0
[info]   | | | | +-com.google.http-client:google-http-client-jackson2:1.22.0
[info]   | | | | | +-com.fasterxml.jackson.core:jackson-core:2.1.3 (evicted by: 2.6.1)
[info]   | | | | | +-com.fasterxml.jackson.core:jackson-core:2.6.1
[info]   | | | | | +-com.google.http-client:google-http-client:1.22.0
[info]   | | | | |   +-com.google.code.findbugs:jsr305:1.3.9
[info]   | | | | |   +-org.apache.httpcomponents:httpclient:4.0.1
[info]   | | | | |     +-commons-codec:commons-codec:1.3 (evicted by: 1.9)
[info]   | | | | |     +-commons-codec:commons-codec:1.9
[info]   | | | | |     +-commons-logging:commons-logging:1.1.1
[info]   | | | | |     +-org.apache.httpcomponents:httpcore:4.0.1
[info]   | | | | |
[info]   | | | | +-com.google.oauth-client:google-oauth-client:1.22.0
[info]   | | | |   +-com.google.code.findbugs:jsr305:1.3.9
[info]   | | | |   +-com.google.http-client:google-http-client:1.22.0
[info]   | | | |     +-com.google.code.findbugs:jsr305:1.3.9
[info]   | | | |     +-org.apache.httpcomponents:httpclient:4.0.1
[info]   | | | |       +-commons-codec:commons-codec:1.3 (evicted by: 1.9)
[info]   | | | |       +-commons-codec:commons-codec:1.9
[info]   | | | |       +-commons-logging:commons-logging:1.1.1
[info]   | | | |       +-org.apache.httpcomponents:httpcore:4.0.1
[info]   | | | |
[info]   | | | +-com.google.guava:guava:21.0
[info]   | | | +-com.google.http-client:google-http-client-jackson2:1.22.0
[info]   | | | | +-com.fasterxml.jackson.core:jackson-core:2.1.3 (evicted by: 2.6.1)
[info]   | | | | +-com.fasterxml.jackson.core:jackson-core:2.6.1
[info]   | | | | +-com.google.http-client:google-http-client:1.22.0
[info]   | | | |   +-com.google.code.findbugs:jsr305:1.3.9
[info]   | | | |   +-org.apache.httpcomponents:httpclient:4.0.1
[info]   | | | |     +-commons-codec:commons-codec:1.3 (evicted by: 1.9)
[info]   | | | |     +-commons-codec:commons-codec:1.9
[info]   | | | |     +-commons-logging:commons-logging:1.1.1
[info]   | | | |     +-org.apache.httpcomponents:httpcore:4.0.1
[info]   | | | |
[info]   | | | +-com.google.inject.extensions:guice-assistedinject:4.0
[info]   | | | | +-com.google.inject:guice:4.0
[info]   | | | |   +-aopalliance:aopalliance:1.0
[info]   | | | |   +-com.google.guava:guava:16.0.1 (evicted by: 21.0)
[info]   | | | |   +-com.google.guava:guava:21.0
[info]   | | | |   +-javax.inject:javax.inject:1
[info]   | | | |
[info]   | | | +-com.google.inject.extensions:guice-multibindings:4.0
[info]   | | | | +-com.google.inject:guice:4.0
[info]   | | | |   +-aopalliance:aopalliance:1.0
[info]   | | | |   +-com.google.guava:guava:16.0.1 (evicted by: 21.0)
[info]   | | | |   +-com.google.guava:guava:21.0
[info]   | | | |   +-javax.inject:javax.inject:1
[info]   | | | |
[info]   | | | +-com.google.inject:guice:4.0
[info]   | | | | +-aopalliance:aopalliance:1.0
[info]   | | | | +-com.google.guava:guava:16.0.1 (evicted by: 21.0)
[info]   | | | | +-com.google.guava:guava:21.0
[info]   | | | | +-javax.inject:javax.inject:1
[info]   | | | |
[info]   | | | +-commons-beanutils:commons-beanutils:1.9.2
[info]   | | | | +-commons-logging:commons-logging:1.1.1
[info]   | | | |
[info]   | | | +-commons-collections:commons-collections:3.2.2
[info]   | | | +-commons-configuration:commons-configuration:1.10
[info]   | | | | +-commons-lang:commons-lang:2.5
[info]   | | | | +-commons-lang:commons-lang:2.6 (evicted by: 2.5)
[info]   | | | | +-commons-logging:commons-logging:1.1.1
[info]   | | | |
[info]   | | | +-commons-lang:commons-lang:2.5
[info]   | | | +-commons-lang:commons-lang:2.6 (evicted by: 2.5)
[info]   | | | +-joda-time:joda-time:2.8.2 (evicted by: 2.9.2)
[info]   | | | +-joda-time:joda-time:2.9.2
[info]   | | | +-net.sf.opencsv:opencsv:1.8
[info]   | | | +-org.slf4j:slf4j-api:1.7.7
[info]   | | |
[info]   | | +-com.google.http-client:google-http-client:1.22.0
[info]   | | | +-com.google.code.findbugs:jsr305:1.3.9
[info]   | | | +-org.apache.httpcomponents:httpclient:4.0.1
[info]   | | |   +-commons-codec:commons-codec:1.3 (evicted by: 1.9)
[info]   | | |   +-commons-codec:commons-codec:1.9
[info]   | | |   +-commons-logging:commons-logging:1.1.1
[info]   | | |   +-org.apache.httpcomponents:httpcore:4.0.1
[info]   | | |
[info]   | | +-commons-discovery:commons-discovery:0.4
[info]   | | | +-commons-logging:commons-logging:1.0.4 (evicted by: 1.1.1)
[info]   | | | +-commons-logging:commons-logging:1.1.1
[info]   | | |
[info]   | | +-javax.xml:jaxrpc-api:1.1
[info]   | | +-org.apache.axis:axis:1.4
[info]   | | +-wsdl4j:wsdl4j:1.6.2
[info]   | |
[info]   | +-com.google.api-ads:ads-lib:3.1.0
[info]   |   +-com.google.api-client:google-api-client:1.22.0
[info]   |   | +-com.google.guava:guava-jdk5:17.0
[info]   |   | +-com.google.http-client:google-http-client-jackson2:1.22.0
[info]   |   | | +-com.fasterxml.jackson.core:jackson-core:2.1.3 (evicted by: 2.6.1)
[info]   |   | | +-com.fasterxml.jackson.core:jackson-core:2.6.1
[info]   |   | | +-com.google.http-client:google-http-client:1.22.0
[info]   |   | |   +-com.google.code.findbugs:jsr305:1.3.9
[info]   |   | |   +-org.apache.httpcomponents:httpclient:4.0.1
[info]   |   | |     +-commons-codec:commons-codec:1.3 (evicted by: 1.9)
[info]   |   | |     +-commons-codec:commons-codec:1.9
[info]   |   | |     +-commons-logging:commons-logging:1.1.1
[info]   |   | |     +-org.apache.httpcomponents:httpcore:4.0.1
[info]   |   | |
[info]   |   | +-com.google.oauth-client:google-oauth-client:1.22.0
[info]   |   |   +-com.google.code.findbugs:jsr305:1.3.9
[info]   |   |   +-com.google.http-client:google-http-client:1.22.0
[info]   |   |     +-com.google.code.findbugs:jsr305:1.3.9
[info]   |   |     +-org.apache.httpcomponents:httpclient:4.0.1
[info]   |   |       +-commons-codec:commons-codec:1.3 (evicted by: 1.9)
[info]   |   |       +-commons-codec:commons-codec:1.9
[info]   |   |       +-commons-logging:commons-logging:1.1.1
[info]   |   |       +-org.apache.httpcomponents:httpcore:4.0.1
[info]   |   |
[info]   |   +-com.google.guava:guava:21.0
[info]   |   +-com.google.http-client:google-http-client-jackson2:1.22.0
[info]   |   | +-com.fasterxml.jackson.core:jackson-core:2.1.3 (evicted by: 2.6.1)
[info]   |   | +-com.fasterxml.jackson.core:jackson-core:2.6.1
[info]   |   | +-com.google.http-client:google-http-client:1.22.0
[info]   |   |   +-com.google.code.findbugs:jsr305:1.3.9
[info]   |   |   +-org.apache.httpcomponents:httpclient:4.0.1
[info]   |   |     +-commons-codec:commons-codec:1.3 (evicted by: 1.9)
[info]   |   |     +-commons-codec:commons-codec:1.9
[info]   |   |     +-commons-logging:commons-logging:1.1.1
[info]   |   |     +-org.apache.httpcomponents:httpcore:4.0.1
[info]   |   |
[info]   |   +-com.google.inject.extensions:guice-assistedinject:4.0
[info]   |   | +-com.google.inject:guice:4.0
[info]   |   |   +-aopalliance:aopalliance:1.0
[info]   |   |   +-com.google.guava:guava:16.0.1 (evicted by: 21.0)
[info]   |   |   +-com.google.guava:guava:21.0
[info]   |   |   +-javax.inject:javax.inject:1
[info]   |   |
[info]   |   +-com.google.inject.extensions:guice-multibindings:4.0
[info]   |   | +-com.google.inject:guice:4.0
[info]   |   |   +-aopalliance:aopalliance:1.0
[info]   |   |   +-com.google.guava:guava:16.0.1 (evicted by: 21.0)
[info]   |   |   +-com.google.guava:guava:21.0
[info]   |   |   +-javax.inject:javax.inject:1
[info]   |   |
[info]   |   +-com.google.inject:guice:4.0
[info]   |   | +-aopalliance:aopalliance:1.0
[info]   |   | +-com.google.guava:guava:16.0.1 (evicted by: 21.0)
[info]   |   | +-com.google.guava:guava:21.0
[info]   |   | +-javax.inject:javax.inject:1
[info]   |   |
[info]   |   +-commons-beanutils:commons-beanutils:1.9.2
[info]   |   | +-commons-logging:commons-logging:1.1.1
[info]   |   |
[info]   |   +-commons-collections:commons-collections:3.2.2
[info]   |   +-commons-configuration:commons-configuration:1.10
[info]   |   | +-commons-lang:commons-lang:2.5
[info]   |   | +-commons-lang:commons-lang:2.6 (evicted by: 2.5)
[info]   |   | +-commons-logging:commons-logging:1.1.1
[info]   |   |
[info]   |   +-commons-lang:commons-lang:2.5
[info]   |   +-commons-lang:commons-lang:2.6 (evicted by: 2.5)
[info]   |   +-joda-time:joda-time:2.8.2 (evicted by: 2.9.2)
[info]   |   +-joda-time:joda-time:2.9.2
[info]   |   +-net.sf.opencsv:opencsv:1.8
[info]   |   +-org.slf4j:slf4j-api:1.7.7
[info]   |
[info]   +-com.google.api-client:google-api-client-gson:1.22.0
[info]   | +-com.google.api-client:google-api-client:1.22.0
[info]   | | +-com.google.guava:guava-jdk5:17.0
[info]   | | +-com.google.http-client:google-http-client-jackson2:1.22.0
[info]   | | | +-com.fasterxml.jackson.core:jackson-core:2.1.3 (evicted by: 2.6.1)
[info]   | | | +-com.fasterxml.jackson.core:jackson-core:2.6.1
[info]   | | | +-com.google.http-client:google-http-client:1.22.0
[info]   | | |   +-com.google.code.findbugs:jsr305:1.3.9
[info]   | | |   +-org.apache.httpcomponents:httpclient:4.0.1
[info]   | | |     +-commons-codec:commons-codec:1.3 (evicted by: 1.9)
[info]   | | |     +-commons-codec:commons-codec:1.9
[info]   | | |     +-commons-logging:commons-logging:1.1.1
[info]   | | |     +-org.apache.httpcomponents:httpcore:4.0.1
[info]   | | |
[info]   | | +-com.google.oauth-client:google-oauth-client:1.22.0
[info]   | |   +-com.google.code.findbugs:jsr305:1.3.9
[info]   | |   +-com.google.http-client:google-http-client:1.22.0
[info]   | |     +-com.google.code.findbugs:jsr305:1.3.9
[info]   | |     +-org.apache.httpcomponents:httpclient:4.0.1
[info]   | |       +-commons-codec:commons-codec:1.3 (evicted by: 1.9)
[info]   | |       +-commons-codec:commons-codec:1.9
[info]   | |       +-commons-logging:commons-logging:1.1.1
[info]   | |       +-org.apache.httpcomponents:httpcore:4.0.1
[info]   | |
[info]   | +-com.google.http-client:google-http-client-gson:1.22.0
[info]   |   +-com.google.code.gson:gson:2.1
[info]   |   +-com.google.http-client:google-http-client:1.22.0
[info]   |     +-com.google.code.findbugs:jsr305:1.3.9
[info]   |     +-org.apache.httpcomponents:httpclient:4.0.1
[info]   |       +-commons-codec:commons-codec:1.3 (evicted by: 1.9)
[info]   |       +-commons-codec:commons-codec:1.9
[info]   |       +-commons-logging:commons-logging:1.1.1
[info]   |       +-org.apache.httpcomponents:httpcore:4.0.1
[info]   |
[info]   +-com.google.apis:google-api-services-analyticsreporting:v4-rev12-1.22.0
[info]   | +-com.google.api-client:google-api-client:1.22.0
[info]   |   +-com.google.guava:guava-jdk5:17.0
[info]   |   +-com.google.http-client:google-http-client-jackson2:1.22.0
[info]   |   | +-com.fasterxml.jackson.core:jackson-core:2.1.3 (evicted by: 2.6.1)
[info]   |   | +-com.fasterxml.jackson.core:jackson-core:2.6.1
[info]   |   | +-com.google.http-client:google-http-client:1.22.0
[info]   |   |   +-com.google.code.findbugs:jsr305:1.3.9
[info]   |   |   +-org.apache.httpcomponents:httpclient:4.0.1
[info]   |   |     +-commons-codec:commons-codec:1.3 (evicted by: 1.9)
[info]   |   |     +-commons-codec:commons-codec:1.9
[info]   |   |     +-commons-logging:commons-logging:1.1.1
[info]   |   |     +-org.apache.httpcomponents:httpcore:4.0.1
[info]   |   |
[info]   |   +-com.google.oauth-client:google-oauth-client:1.22.0
[info]   |     +-com.google.code.findbugs:jsr305:1.3.9
[info]   |     +-com.google.http-client:google-http-client:1.22.0
[info]   |       +-com.google.code.findbugs:jsr305:1.3.9
[info]   |       +-org.apache.httpcomponents:httpclient:4.0.1
[info]   |         +-commons-codec:commons-codec:1.3 (evicted by: 1.9)
[info]   |         +-commons-codec:commons-codec:1.9
[info]   |         +-commons-logging:commons-logging:1.1.1
[info]   |         +-org.apache.httpcomponents:httpcore:4.0.1
[info]   |
[info]   +-com.google.oauth-client:google-oauth-client-java6:1.22.0
[info]   | +-com.google.oauth-client:google-oauth-client:1.22.0
[info]   |   +-com.google.code.findbugs:jsr305:1.3.9
[info]   |   +-com.google.http-client:google-http-client:1.22.0
[info]   |     +-com.google.code.findbugs:jsr305:1.3.9
[info]   |     +-org.apache.httpcomponents:httpclient:4.0.1
[info]   |       +-commons-codec:commons-codec:1.3 (evicted by: 1.9)
[info]   |       +-commons-codec:commons-codec:1.9
[info]   |       +-commons-logging:commons-logging:1.1.1
[info]   |       +-org.apache.httpcomponents:httpcore:4.0.1
[info]   |
[info]   +-com.google.oauth-client:google-oauth-client-jetty:1.22.0
[info]   | +-com.google.oauth-client:google-oauth-client-java6:1.22.0
[info]   | | +-com.google.oauth-client:google-oauth-client:1.22.0
[info]   | |   +-com.google.code.findbugs:jsr305:1.3.9
[info]   | |   +-com.google.http-client:google-http-client:1.22.0
[info]   | |     +-com.google.code.findbugs:jsr305:1.3.9
[info]   | |     +-org.apache.httpcomponents:httpclient:4.0.1
[info]   | |       +-commons-codec:commons-codec:1.3 (evicted by: 1.9)
[info]   | |       +-commons-codec:commons-codec:1.9
[info]   | |       +-commons-logging:commons-logging:1.1.1
[info]   | |       +-org.apache.httpcomponents:httpcore:4.0.1
[info]   | |
[info]   | +-org.mortbay.jetty:jetty:6.1.26
[info]   |   +-org.mortbay.jetty:jetty-util:6.1.26
[info]   |   +-org.mortbay.jetty:servlet-api:2.5-20081211
[info]   |
[info]   +-com.jason-goodwin:authentikat-jwt_2.11:0.4.1 [S]
[info]   | +-commons-codec:commons-codec:1.9
[info]   | +-org.json4s:json4s-jackson_2.11:3.2.10 [S]
[info]   | | +-com.fasterxml.jackson.core:jackson-databind:2.3.1
[info]   | | | +-com.fasterxml.jackson.core:jackson-annotations:2.3.0
[info]   | | | +-com.fasterxml.jackson.core:jackson-core:2.3.1 (evicted by: 2.6.1)
[info]   | | | +-com.fasterxml.jackson.core:jackson-core:2.6.1
[info]   | | |
[info]   | | +-org.json4s:json4s-core_2.11:3.2.10 [S]
[info]   | |   +-com.thoughtworks.paranamer:paranamer:2.6
[info]   | |   +-org.json4s:json4s-ast_2.11:3.2.10 [S]
[info]   | |   +-org.scala-lang:scalap:2.11.0 (evicted by: 2.11.1)
[info]   | |   +-org.scala-lang:scalap:2.11.1
[info]   | |     +-org.scala-lang:scala-compiler:2.11.1 [S]
[info]   | |       +-org.scala-lang.modules:scala-parser-combinators_2.11:1.0.1 [S]
[info]   | |       +-org.scala-lang.modules:scala-xml_2.11:1.0.2 [S]
[info]   | |       +-org.scala-lang:scala-reflect:2.11.1 (evicted by: 2.11.2)
[info]   | |       +-org.scala-lang:scala-reflect:2.11.2 [S]
[info]   | |
[info]   | +-org.json4s:json4s-native_2.11:3.2.10 [S]
[info]   |   +-org.json4s:json4s-core_2.11:3.2.10 [S]
[info]   |     +-com.thoughtworks.paranamer:paranamer:2.6
[info]   |     +-org.json4s:json4s-ast_2.11:3.2.10 [S]
[info]   |     +-org.scala-lang:scalap:2.11.0 (evicted by: 2.11.1)
[info]   |     +-org.scala-lang:scalap:2.11.1
[info]   |       +-org.scala-lang:scala-compiler:2.11.1 [S]
[info]   |         +-org.scala-lang.modules:scala-parser-combinators_2.11:1.0.1 [S]
[info]   |         +-org.scala-lang.modules:scala-xml_2.11:1.0.2 [S]
[info]   |         +-org.scala-lang:scala-reflect:2.11.1 (evicted by: 2.11.2)
[info]   |         +-org.scala-lang:scala-reflect:2.11.2 [S]
[info]   |
[info]   +-com.tdunning:t-digest:3.1
[info]   +-com.typesafe.akka:akka-actor_2.11:2.3.6 [S]
[info]   | +-com.typesafe:config:1.2.1
[info]   |
[info]   +-com.typesafe.akka:akka-slf4j_2.11:2.3.6 [S]
[info]   | +-com.typesafe.akka:akka-actor_2.11:2.3.6 [S]
[info]   | | +-com.typesafe:config:1.2.1
[info]   | |
[info]   | +-org.slf4j:slf4j-api:1.7.5 (evicted by: 1.7.7)
[info]   | +-org.slf4j:slf4j-api:1.7.7
[info]   |
[info]   +-net.liftweb:lift-json_2.11:2.6 [S]
[info]   | +-com.thoughtworks.paranamer:paranamer:2.4.1 (evicted by: 2.6)
[info]   | +-com.thoughtworks.paranamer:paranamer:2.6
[info]   | +-org.scala-lang:scalap:2.11.1
[info]   |   +-org.scala-lang:scala-compiler:2.11.1 [S]
[info]   |     +-org.scala-lang.modules:scala-parser-combinators_2.11:1.0.1 [S]
[info]   |     +-org.scala-lang.modules:scala-xml_2.11:1.0.2 [S]
[info]   |     +-org.scala-lang:scala-reflect:2.11.1 (evicted by: 2.11.2)
[info]   |     +-org.scala-lang:scala-reflect:2.11.2 [S]
[info]   |
[info]   +-org.bouncycastle:bcprov-jdk15on:1.56
[info]   +-org.elasticsearch:elasticsearch-spark_2.11:2.2.0
[info]   +-org.mashupbots.socko:socko-webserver_2.11:0.6.0 [S]
[info]   | +-ch.qos.logback:logback-classic:1.0.9
[info]   | | +-ch.qos.logback:logback-core:1.0.9
[info]   | | +-org.slf4j:slf4j-api:1.7.2 (evicted by: 1.7.7)
[info]   | | +-org.slf4j:slf4j-api:1.7.5 (evicted by: 1.7.7)
[info]   | | +-org.slf4j:slf4j-api:1.7.7
[info]   | |
[info]   | +-com.googlecode.concurrentlinkedhashmap:concurrentlinkedhashmap-lru:1.3.2
[info]   | +-com.typesafe.akka:akka-actor_2.11:2.3.6 [S]
[info]   | | +-com.typesafe:config:1.2.1
[info]   | |
[info]   | +-com.typesafe.akka:akka-slf4j_2.11:2.3.6 [S]
[info]   | | +-com.typesafe.akka:akka-actor_2.11:2.3.6 [S]
[info]   | | | +-com.typesafe:config:1.2.1
[info]   | | |
[info]   | | +-org.slf4j:slf4j-api:1.7.5 (evicted by: 1.7.7)
[info]   | | +-org.slf4j:slf4j-api:1.7.7
[info]   | |
[info]   | +-io.netty:netty-all:4.0.23.Final
[info]   | +-org.eclipse.jetty.npn:npn-api:1.1.0.v20120525
[info]   | +-org.scala-lang:scala-reflect:2.11.2 [S]
[info]   |
[info]   +-org.parboiled:parboiled_2.11:2.0.1 [S]
[info]   | +-com.chuusai:shapeless_2.11:2.0.0 [S]
[info]   |
[info]   +-org.scalaj:scalaj-http_2.11:2.3.0 [S]
[info]   +-wabisabi:wabisabi_2.11:2.1.3 [S]
[info]     +-com.netaporter:scala-uri_2.11:0.4.3 [S]
[info]     | +-org.parboiled:parboiled_2.11:2.0.1 [S]
[info]     |   +-com.chuusai:shapeless_2.11:2.0.0 [S]
[info]     |
[info]     +-net.databinder.dispatch:dispatch-core_2.11:0.11.2 [S]
[info]     | +-com.ning:async-http-client:1.8.10
[info]     | | +-io.netty:netty:3.9.2.Final
[info]     | | +-org.slf4j:slf4j-api:1.7.5 (evicted by: 1.7.7)
[info]     | | +-org.slf4j:slf4j-api:1.7.7
[info]     | |
[info]     | +-org.scala-lang.modules:scala-xml_2.11:1.0.1 (evicted by: 1.0.2)
[info]     | +-org.scala-lang.modules:scala-xml_2.11:1.0.2 [S]
[info]     |
[info]     +-org.clapper:grizzled-slf4j_2.11:1.0.2 [S]
[info]       +-org.slf4j:slf4j-api:1.7.7
[info]
[success] Total time: 9 s, completed Mar 9, 2017 11:34:43 AM

**Comment by jradcliff** [comment]
Hi Richard,

I see that you are using `commons-configuration:commons-configuration:1.10`, which contains the `MapConfiguration` constructor that takes a `java.util.Properties`, so I'm also a bit confused by this error.

http://commons.apache.org/proper/commons-configuration/javadocs/v1.10/apidocs/org/apache/commons/configuration/MapConfiguration.html#MapConfiguration(java.util.Properties)

Were you able to successfully use a previous version of `adwords-axis`? If so, could you let me know which version that was?

Thanks,
Josh, AdWords API Team

**Comment by rsiebeling** [comment]
Hi Josh,

yes I'm confused too, the method is in the package... I don't understand.
This is the first time I'm using the Google Adwords API. So no, I've not tried with an earlier version,

regards,
Richard

**Comment by rsiebeling** [comment]
ah I think I found it, looking into the Spark jar thats included in the classpath, there is another commons configuration but version 1.6 and this version doesn't have the properties initializator.
I'll try to compile a version without the 1.6 version

**Comment by jradcliff** [comment]
Hi Richard,

Did the fix you proposed work? If so, could you close this issue?

Thanks,
Josh, AdWords API Team

**Comment by rsiebeling** [comment]
Hi Josh,

yes it worked, I'll close the issue,
regards,

Richard

**Comment by rsiebeling** [comment]
-
