### ISSUE TITLE
Retrieve additional fields like displayFieldName and FieldBehaviour from getReportFields

### ISSUE THREAD

**Issue by rsiebeling** [googleads/googleads-java-lib#108]
Hi,

according to the documentation only the fieldName, fieldType and enumValues are available when using the results from getReportFields.
I'd like to use the displayFieldName and the fieldBehaviour (and possible a description but that doesn't seem available), is there a possibility to get these values?

thanks in advance,
Richard

**Comment by jradcliff** [comment]
Hi,

The [ReportDefinitionField object](https://developers.google.com/adwords/api/docs/reference/v201702/ReportDefinitionService.ReportDefinitionField) has most of the attributes you're looking for, e.g.:

- [getFieldBehavior()](https://github.com/googleads/googleads-java-lib/blob/master/modules/adwords_axis/src/main/java/com/google/api/ads/adwords/axis/v201702/cm/ReportDefinitionField.java#L254)
- [getDisplayFieldName()](https://github.com/googleads/googleads-java-lib/blob/master/modules/adwords_axis/src/main/java/com/google/api/ads/adwords/axis/v201702/cm/ReportDefinitionField.java#L176)

The field descriptions aren't returned by `ReportDefinitionService`. However, you can download a CSV version of the field documentation either on each individual report's page under [Reports](https://developers.google.com/adwords/api/docs/appendix/reports), or all in a single file from the [All reports page](https://developers.google.com/adwords/api/docs/appendix/reports/all-reports).

I think that covers your questions, but feel free to reopen this if I missed something.

Cheers,
Josh, AdWords API Team

**Comment by rsiebeling** [comment]
thanks for the info, this worked excellent.
I had trouble finding the documentation but should have looked into the
sourcecode,

thanks again,
Richard
