### ISSUE TITLE
Feature Request: DFP Page Interface

### ISSUE THREAD

**Issue by yeison** [googleads/googleads-java-lib#109]
It would be great if all of the Page types in DFP inherited from a common Page interface. It would help to greatly reduce the amount of duplicated code in my application.

**Comment by christopherseeley** [comment]
This is the same scenario as #96. The Page types are all generated from the WSDL, so this would require some post-processing on the generated stubs.

Marking as an enhancement and we'll investigate along with #96.

**Comment by christopherseeley** [comment]
Fixed in v3.3.0

**Comment by yeison** [comment]
NIIICEE
