### ISSUE TITLE
Flexibility to modify the baseURL

### ISSUE THREAD

**Issue by Avinash-h** [googleads/googleads-java-lib#110]
We need the functionality for changing baseURL of adwords-axis APIs. Since our service won't able to make request directly to HTTPS. We are making request via forward proxy and internally we pass in port 443.

Example: 
our servers can't make request directly to 
https://adwords.google.com/*
we make request to http://adwords.google.com:443/*

Since all the strings are hardcoded, this library is unusable for us.
for ex:
in file LabelServiceSoapBindingStub.java
`_call.setOperationName(new javax.xml.namespace.QName("https://adwords.google.com/api/adwords/cm/v201609", "get"));`

instead we can introduce baseURL and use the function:
`_call.setOperationName(new javax.xml.namespace.QName(baseURL + "api/adwords/cm/v201609", "get"));`

Let me know if this can be done. 
I can make the changes and create PR for this.

**Comment by jradcliff** [comment]
Hi,

The library already supports using a proxy. Please check out the ['Using a proxy' section of the README](https://github.com/googleads/googleads-java-lib#using-a-proxy) and let me know if you have any questions.

Thanks,
Josh, AdWords API Team
