### ISSUE TITLE
LineItem update is clearing field values in DFP

### ISSUE THREAD

**Issue by yeison** [googleads/googleads-java-lib#112]
When I called LineItemServiceInterface.updateLineItems(LineItem[]) it cleared the Creative Targeting on the LineItem.

**Comment by christopherseeley** [comment]
This probably isn't specific to the java client library. Can you please post on the [developer forum](https://groups.google.com/forum/#!forum/google-doubleclick-for-publishers-api) instead? If you have SOAP logs demonstrating the issue that will help us debug. Thanks!
