### ISSUE TITLE
Question: Services that RateLimiter Covers

### ISSUE THREAD

**Issue by laiyhman** [googleads/googleads-java-lib#113]
Hi,

CampaignService and ReportDownloader are mentioned in the "Basic Usage" here https://github.com/googleads/googleads-java-lib/tree/master/extensions/adwords_rate_limiter

Would like to know if the RateLimiter covers other services such as CustomerService and ManagedCustomerService as well?

**Comment by chenzhuo914** [comment]
All AdWords API "services" (such as CustomerService and ManagedCustomerService) can use RateLimiter in the same way as CampaignService described in the "Basic Usage" section.

Please let us know if you encounter any problems or have further questions. Thanks!

**Comment by chenzhuo914** [comment]
Closing as there's no follow up required at this time. Please feel free to reopen if you have further questions.
