### ISSUE TITLE
Find Products in a particular ProductPartitionNode 

### ISSUE THREAD

**Issue by applecrusher** [googleads/googleads-java-lib#116]
Is there anyway to see what products are in a particular product partition node?
Is there a way to tell whether a particular product partition node has products or is empty?

Thanks!

**Comment by jradcliff** [comment]
Hi,

Unfortunately, you can't get product-level information from `AdGroupCriterionService`. The closest you can get is to use the [SHOPPING_PERFORMANCE_REPORT](https://developers.google.com/adwords/api/docs/appendix/reports/shopping-performance-report), which has fields for various product attributes such as `OfferId`, `CategoryL1`, `ProductTypeL1`, etc. However,  that report has the following limitations:

1.  The report will only return rows for products with impressions during the report date range.
2.  The report does not include the criterion ID of the corresponding `ProductPartition`, although we are considering adding it.

Another option would be to use the [Content API for Shopping](https://developers.google.com/shopping-content/v2/quickstart), but even with that approach, you would need to use the attributes of each product to match it with the corresponding `ProductPartition` based on the partition's `caseValue`, which won't be trivial.

Thanks,
Josh Radcliff, AdWords API Team
