### ISSUE TITLE
Mobile and Desktop AdGroup Bid Modifiers not being unset when removed

### ISSUE THREAD

**Issue by applecrusher** [googleads/googleads-java-lib#118]
I have been able to successfully get bids and set bids from the AdGroup level. However, I am having a lot of issues removing the bids and the bids react differently. When I use the `Operator.REMOVE` on tablet bid adjustments, the bid becomes unset. However on the mobile and desktop bids they do not. Is there a way to unset AdGroup Bid Modifiers that I am not aware about or is this an issue with the API?

**Comment by jradcliff** [comment]
Hi,

Since this question is not specific to the Java client library, please post it to the
[AdWords API Forum](https://groups.google.com/forum/#!forum/adwords-api) and one of my teammates there will be glad to help.

Thanks,
Josh, AdWords API Team
