### ISSUE TITLE
compiled jar download

### ISSUE THREAD

**Issue by arch9745** [googleads/googleads-java-lib#119]
Is there a compiled jar of the library available for downloading? All the downloads I have seen so far have source code that must be compiled.

**Comment by jradcliff** [comment]
Hi,

The easiest approach is to use Maven as described in the [README](https://github.com/googleads/googleads-java-lib/blob/master/README.md#getting-started). If Maven is not an option, then check out the archives under each release on the [Releases page](https://github.com/googleads/googleads-java-lib/releases), which will include a file named

    adwords-axis-jars-and-examples-X.Y.Z.tar.gz

Within that archive, there is a `lib` directory that contains all required JARs, including compiled classes for the library itself (`ads-lib-X.Y.Z.jar`, `ads-lib-axis-X.Y.Z.jar`, `adwords-axis-X.Y.Z.jar`).

The archive will also contain a `src` directory containing the source for examples. You can ignore that folder if you just want the dependencies required to use the library in your own project.

Thanks,
Josh, AdWords API Team
