### ISSUE TITLE
Option to provide custom http client when using client library?

### ISSUE THREAD

**Issue by hrishikeshs** [googleads/googleads-java-lib#120]
Hi folks,
I'm using google's java client library to create adwords campaigns. This works fine during development, but when I deploy my service to production, all our outgoing requests need to pass through our own proxy. Our proxy examines some of our custom http headers and forwards the request to the Internet. My questions are:
 1. is it possible to use my own custom http client instead of the one that ships with the library to make the http request ? 
2. in case 1. is not possible, is it possible to add custom http headers to the requests made by the client?

**Comment by jradcliff** [comment]
Hi,

The client library doesn't support plugging in your own HTTP client, but have you looked into doing this by creating and registering your own `ProxySelector`, as described in the [Java Networking and Proxies guide](https://docs.oracle.com/javase/8/docs/technotes/guides/net/proxies.html) (item #4)?

Thanks,
Josh, AdWords API Team

**Comment by hrishikeshs** [comment]
Hi Josh,
Thanks for pointing me to the  `ProxySelector` docs.. looks like I can use it for my use case 👍

**Comment by jradcliff** [comment]
Hi,

Glad to hear that'll work! I'll close this issue, but feel free to reopen if you have further questions or find `ProxySelector` doesn't address all of your requirements.

Cheers,
Josh, AdWords API Team
