### ISSUE TITLE
No Ability to Specify ServiceAccountUser in OfflineCredentials Builder

### ISSUE THREAD

**Issue by KarmicJohn** [googleads/googleads-java-lib#122]
I am receiving an AuthenticationError.NOT_ADS_USER when using a ServiceAccount to access our MCC Account.

This is what I have in ads.properties:
`api.adwords.jsonKeyFilePath=src/main/resources/JSONFILENAME.json
api.adwords.developerToken=DEVELOPERTOKEN
api.adwords.clientCustomerId=CUSTOMERID`

This returns an accessToken, but the serviceAccountUser is null on the Credential from the Builder, created as follows:
`Credential oAuth2Credential = new OfflineCredentials.Builder()
                .forApi(OfflineCredentials.Api.ADWORDS)
                .fromFile()
                .build()
                .generateCredential();`

I've looked through the source code and don't see where it would pull serviceAccountUser from the properties file or JSON file if I were to add it there. How can I specify the user to impersonate when making the call? Is there some other reason this AuthenticationError would occur? 

I'm creating this as an issue on the Java Lib, as other libs have the ability to specify.

Appreciate any support on this issue.

Thanks!
John

**Comment by KarmicJohn** [comment]
Update here:
This does appear to be a bug or at least something that was left out or not documented to where it's clear how to get that ServiceAccountUser set on the generated GoogleCredential.

When I set a breakpoint at line 223 of OfflineCredentials, just before callRefreshToken is called, I can force the a credential.setServiceAccountUser to a user in my domain that has access to our MCC account and I am able to connect and no longer get the Auth error.

**Comment by jradcliff** [comment]
Hi,

As you noted, we're using [GoogleCredential](https://github.com/google/google-api-java-client/blob/dev/google-api-client/src/main/java/com/google/api/client/googleapis/auth/oauth2/GoogleCredential.java) from the Google OAuth2 library. Unfortunately, there are two challenges when it comes to setting the `serviceAccountUser` here:

1. The `serviceAccountUser` is immutable on a `GoogleCredential`. It can only be set on a `GoogleCredential.Builder`.
1. `GoogleCredential` does not provide a `fromStream` method that returns a *builder*.

As a result, it looks like the only option is to essentially duplicate the code in [`GoogleCredential.fromStreamServiceAccount`](https://github.com/google/google-api-java-client/blob/dev/google-api-client/src/main/java/com/google/api/client/googleapis/auth/oauth2/GoogleCredential.java#L820) and set the `serviceAccountUser` on the builder in that duplicated code.

I'll look into enhancing `OfflineCredentials` to support this use case. In the meantime, if you need this urgently, you could implement the above approach in your application.

Thanks,
Josh, AdWords API Team

**Comment by KarmicJohn** [comment]
Thanks, @jradcliff!

Exactly the problems I ran into and realized as I dug in that it appeared to be more a shortcoming of the Java OAuth2 library and not a super-easy fix for the Adwords library. (without replicating the OAuth2 code in the Adwords library, to provide for this capability)

We have added an Adwords Helper class that basically duplicates the fromStream code from the OAuth library, enabling setting the serviceAccountUser at build time.

An easy fix once we dug in, but seem to be a lot of reports of that AuthenticationError.NOT_ADS_USER and figured it would be good to get the word out on what's causing that error. (at least for those that have configured their service account and G Suite account correctly)

Happy to share that code if others stumble upon this in the mean time...

Have a great day!

**Comment by jradcliff** [comment]
Hi,

I plan to enhance the library to support this use case, but if you wouldn't mind sharing your code here, that would definitely be helpful for other users in the meantime.

Thanks!
Josh, AdWords API Team

**Comment by jradcliff** [comment]
Hi,

Fixed in [3.10.0](https://github.com/googleads/googleads-java-lib/releases/tag/3.10.0). See:

- New [`withServiceAccountUser`](https://github.com/googleads/googleads-java-lib/blob/3.10.0/modules/ads_lib/src/main/java/com/google/api/ads/common/lib/auth/OfflineCredentials.java#L476) method on the `OfflineCredentials` builder.
- Updated [service account page](https://github.com/googleads/googleads-java-lib/wiki/API-access-using-own-credentials-(server-to-server-flow)).
- Updated [ads.properties](https://github.com/googleads/googleads-java-lib/blob/master/examples/adwords_axis/src/main/resources/ads.properties) template, which now includes a property for the `serviceAccountUser`.

Cheers,
Josh, AdWords API Team
