### ISSUE TITLE
failure initializing OfflineCredentials$Api

### ISSUE THREAD

**Issue by arch9745** [googleads/googleads-java-lib#123]
We are using the Java client libraries and getting the following error:

java.lang.NoClassDefFoundError: Could not initialize class com.google.api.ads.common.lib.auth.OfflineCredentials$Api

All the jars have been included in the classpath. ads.properties file is all set up. Why it can not initialize and what is it actually not finding? The jar that includes OfflineCredentials$Api is there.

**Comment by jradcliff** [comment]
Hi,

Are you using maven or the jars from the `lib` directory of the tarball?

If you're using maven, could you share the `dependencies` portion of your pom.xml file?

If you're using the jars in the tarball, could you add a statement to print out the classpath (just to be sure) from the [`java.class.path` system property](https://docs.oracle.com/javase/tutorial/essential/environment/sysprop.html), then confirm it actually contains the expected paths?

Thanks,
Josh, AdWords API Team

**Comment by arch9745** [comment]
We are including the jars from the lib directory. The classpath includes the following jars:

adwords-axis-3.4.0.jar
ads-lib-axis-3.4.0.jar
ads-lib-3.4.0.jar
axis-1.4.jar
google-oauth-client-1.22.0.jar
guice-4.0.jar
guava-20.0.jar
javax.inject-1.jar
aopalliance-1.0.jar
slf4j-api-1.7.7.jar
slf4j-log4j12-1.7.7.jar
log4j-1.2.16.jar
commons-configuration-1.10.jar
commons-lang-2.6.jar
google-http-client-1.22.0.jar
commons-logging-1.1.1.jar
google-api-client-1.22.0.jar
google-http-client-jackson2-1.22.0.jar
jackson-core-2.1.3.jar
guice-assistedinject-4.0.jar
jaxrpc-api-1.1.jar
commons-discovery-0.4.jar
wsdl4j-1.6.2.jar
commons-beanutils-1.9.2.jar

Is there a way to find out what the inter dependencies are between the jars? Which jar needs which other jars?

thanks.

**Comment by jradcliff** [comment]
Hi,

You can see the inter-dependencies using maven's `dependency:list` goal. However, since you're not using maven, I just compared your list to the contents of the `lib` directory for version `3.4.0`, and I noticed that you are missing the following entries:

* commons-codec-1.3.jar
* commons-collections-3.2.2.jar
* guice-multibindings-4.0.jar
* httpclient-4.0.1.jar
* httpcore-4.0.1.jar
* joda-time-2.8.2.jar
* jsr305-1.3.9.jar
* opencsv-1.8.jar

Could you try adding those jars and let me know if that resolves the problem?

Thanks,
Josh, AdWords API Team

**Comment by jradcliff** [comment]
Hi,

It's been a while since you raised this. Could you let me know if you resolved this issue?

Thanks,
Josh, AdWords API Team

**Comment by arch9745** [comment]
Thank you Josh for all your help. The problem was the way jboss was handling the dependencies between the jars. Had to run this outside of jboss to get it to work.

**Comment by jradcliff** [comment]
Hi,

Thanks for the update. I'll mark this closed, but if you have any tips for other JBoss users, feel free to add them here.

Cheers,
Josh, AdWords API Team
