### ISSUE TITLE
Support downloading BatchJob results in chunks

### ISSUE THREAD

**Issue by MohaSaid** [googleads/googleads-java-lib#124]
Hi,

While I was working with the following libraries:
- com.google.api-ads : ads-lib : 3.2.0
- com.google.api-ads: adwords-axis : 3.2.0

I was able to get the BatchJobLogger using:
-> batchJobLogger = AdWordsInternals.getInstance().getAdWordsServiceLoggers().getBatchJobLogger();

Now i updated the libraries to:
- com.google.api-ads : ads-lib : 3.7.0
- com.google.api-ads: adwords-axis : 3.7.0

And I'm unable to find a way to get the BatchJobLogger as I used to because the method getAdWordsServiceLoggers() does not exist.

How can I get the BatchJobLogger from AdWordsInternals or another way using those new libraries?

**Comment by jradcliff** [comment]
Hi,

The `BatchJobLogger` offers very specific functionality that the library needs in its batch job utilities. Specifically, it has the methods `logUpload` and `logDownload` that the utility uses when it's uploading operations or downloading results.

Given the above, I'm curious how you were using the `BatchJobLogger` previously. Could you provide some more details so I can figure out the best approach for you going forward?

Thanks,
Josh, AdWords API Team

**Comment by jradcliff** [comment]
Hi,

I just realized that you might be looking for `BatchJobLogger` if you are trying to construct an instance of `BatchJobHelper` or even `BatchJobHelperImpl` yourself. If that's the case, please use the `getUtility` method of `AdWordsServices` instead, as demonstrated in the [CompleteCampaignsUsingBatchJob.java example](https://github.com/googleads/googleads-java-lib/blob/master/examples/adwords_axis/src/main/java/adwords/axis/v201708/campaignmanagement/AddCompleteCampaignsUsingBatchJob.java#L161).

    BatchJobHelper batchJobHelper = adWordsServices.getUtility(session, BatchJobHelper.class);

The `getUtility` method will take care of injecting all of the dependencies for `BatchJobHelper`, including any loggers it requires.

Just thought I'd mention that in case it's helpful. :)

Cheers,
Josh, AdWords API Team

**Comment by MohaSaid** [comment]
Hi,

As you say in your first comment, I'm using the _logDownload_ function of the logger in order to check the logs when downloading results.

I was using the batchjoblogger inside a class, _AdwordsAxisDeserializer_ which has a private batchjoblogger. And how I was using it? I was using it in a function, the specifici code:

```
BatchJobMutateResponse response = new BatchJobMutateResponse();
response.setMutateResults(mutateResults.toArray(new MutateResult[mutateResults.size()]));

batchJobLogger.logDownload(filepath, response, null);
```
But firstly, I had in the constructor of _AdwordsAxisDeserializer_ a batchjoblogger initialization by this way:

`
batchJobLogger = AdWordsInternals.getInstance().getAdWordsServiceLoggers().getBatchJobLogger();`

**Comment by jradcliff** [comment]
Hi,

Thanks for clarifying. It looks like you may have created your own implementation of `BatchJobHelperInterface`, but you are trying to use some of the inner workings of our implementation of that interface.

Could you let me know why you took this approach? Is there some functionality you needed that's missing from the [batch job utility](https://github.com/googleads/googleads-java-lib/wiki/BatchJobHelper-utility-for-AdWords#batchjobhelperinterface)?

Thanks,
Josh, AdWords API Team

**Comment by MohaSaid** [comment]
Hi,

I really did not decide the approach of that class. I just found myself working on that existing project in my company and I had to upgrade the version of the libraries. And that's how I found that problem. I'm trying to keep the structure of the existing code, so I think there must be a way to achieve that. 

So my problem here is how to initialize a batchJobLogger. How can I get it?

Thanks.

**Comment by jradcliff** [comment]
Hi,

Thanks, I definitely understand and sympathize with your situation. Since I'm guessing your immediate goal is to just get things working again, you can use the following approach:

    BatchJobLogger batchJobLogger = AdWordsInternals.getBootstrapper()
        .getInstanceOf(session, BatchJobLogger.class);

Long term, though, I **highly** recommend removing the dependency on `BatchJobLogger` and, more importantly, using the batch job utilities the library provides. If you find that the utility is lacking some functionality, definitely let me know so I can address that gap. I'm always open to suggestions on how to improve the library.

Cheers,
Josh, AdWords API Team

**Comment by MohaSaid** [comment]
Hi Josh,

Thanks for your help. I actually was trying it using:

`BatchJobLogger batchJobLogger = AdWordsService.getBootstrapper()
    .getInstanceOf(session, BatchJobLogger.class);`

But with your approach I think I can get the things working as I want. Tomorrow I will confirm you if it works properly.

**Comment by MohaSaid** [comment]
Hi Josh,

I finally understood the class I had to work with and its usage. In fact, as you said, it was a kind of own implementation of `BatchJobHelperInterface` . The reason of that class was to override `downloadBatchJobMutateResponse` function in order to parameterize it with a integer which represents the number of items to read in the response from adwords. And with this approach instead of reading and process (deserialize) the whole xml response, we only read 5k elements of that, for example. 

After discussing it, I think I am going to create a new class which is going to extend from `BatchJobHelper` and I will try to only override the `downloadBatchJobMutateResponse` method in order to parameterize it with an integer and pass the logic I mentioned before to it. Doing this way I will remove the dependencies I had and I will use the utilities the library provides me.

What do you think about that approach? If you want we can discuss it via email or another way you feel more comfortable. 

Thanks!

**Comment by jradcliff** [comment]
Hi,

Sorry, I didn't notice this update until just now. Your approach sounds good to me.

Stepping back a bit, I can see how adding an option to consume the download response in chunks could be useful to other users. IIRC, Axis tries to unmarshal the *entire* response, so the `BatchJobHelperInterface` might have to do something like:

0. Set `baseIndex` to `0`.
1. Get the substring of `[baseIndex, chunkSize)` from the response.
2. Set `startIndex` to the position of the first opening `<rval>` tag in the substring from step 1.
3. Set `endIndex` to the position after the last closing `</rval>` tag in the substring from step 1.
4. Take the substring of `[startIndex, endIndex)`, add an opening `<mutateResponse>` tag to the beginning and a closing `</mutateResponse>` to the end.
5. Deserialize the string resulting from step 4 and return it to the user.
6. If there are more `<rval>` elements after `endIndex`, set `baseIndex = endIndex` and repeat steps 1-5.

Is that essentially what you're doing in your application?

Thanks,
Josh, AdWords API Team

**Comment by jradcliff** [comment]
Hi,

Could you let me know if the approach I mentioned in my previous comment aligns with your requirements?

Thanks,
Josh, AdWords API Team

**Comment by jradcliff** [comment]
Hi,

Could you please take a look at my last question? Also, I reworded the issue title to reflect the current request.

Thanks,
Josh, AdWords API Team

**Comment by MohaSaid** [comment]
Hi,

Sorry for my late response. Yes, your approach helped me. We can close the issue.

Thank you,

Moha
