### ISSUE TITLE
extensions/adwords_rate_limiter should be on by default

### ISSUE THREAD

**Issue by RichardBradley** [googleads/googleads-java-lib#127]
I think that `extensions/adwords_rate_limiter` should be merged into the main code, so that it is on by default.

It is not easily discoverable, and users might otherwise waste time reimplementing it.

**Comment by jradcliff** [comment]
Hi,

Thanks for the suggestion. We debated including it in the core library, but ultimately decided to keep it separate so people can decide for themselves if they want to use our particular rate limit handler approach. Many users of the library already have their own custom handlers, and we did not want to change the behavior for those users.

That being said, I think it makes sense for the library's [README.md](https://github.com/googleads/googleads-java-lib/blob/master/README.md) to point users to the available extensions for the library. I'll make that change in the next release.

Thanks,
Josh, AdWords API Team

**Comment by RichardBradley** [comment]
Thanks, that sounds good to me.
