### ISSUE TITLE
Update ads-lib dependencies

### ISSUE THREAD

**Issue by peterrobles** [googleads/googleads-java-lib#130]
Using adwords and shopping content API libraries on same project creates a conflict on dependencies.
ads-lib still uses google-api-client 1.22 whilst latest shopping version uses google-api-client 1.23

This ends  up on the necessary dependency not being correctly resolved.

Please update your client libraries so they are compatible 100% and safe to be used on same project

**Comment by jradcliff** [comment]
Hi,

Thanks for pointing this out. I'll look into upgrading the library's dependencies, but in the meantime, would adding a dependency on `google-api-client` 1.23 in *your* project resolve this? With that setup, I would expect maven to use 1.23 and basically ignore the version in the ads-lib module, since the dependency in `ads-lib` is a ["Soft" requirement](https://maven.apache.org/pom.html#Dependency_Version_Requirement_Specification). In fact, I'm a little surprised that maven isn't doing this already when it sees that the Content API library requires 1.23.

Thanks,
Josh, AdWords API Team

**Comment by peterrobles** [comment]
Hi Josh,

Thanks for your reply.
Maven doesn't resolve those dependencies due to order. When I swap the order then Maven resolves google-api-client v 1.23 but for the transitive dependency google-http-client-jackson2 it omits v 1.23 and uses v 1.22 as it's defined on ads-lib in a higher level.

So to summarize I'm better off using content-api v2-rev105-1.22.0 instead of the 1.23 counterpart.

For anyone interested my Google dependencies are:

		<dependency>
			<groupId>com.google.api-ads</groupId>
			<artifactId>ads-lib</artifactId>
			<exclusions>
				<exclusion>
					<groupId>commons-logging</groupId>
					<artifactId>commons-logging</artifactId>
				</exclusion>
			</exclusions>
			<version>${adwords.version}</version>
		</dependency>
		<dependency>
			<groupId>com.google.api-ads</groupId>
			<artifactId>adwords-axis</artifactId>
			<version>${adwords.version}</version>
			<exclusions>
				<exclusion>
					<groupId>commons-logging</groupId>
					<artifactId>commons-logging</artifactId>
				</exclusion>
			</exclusions>
		</dependency>
		<dependency>
			<groupId>com.google.apis</groupId>
			<artifactId>google-api-services-content</artifactId>
			<version>${google-content-api.version}</version>
		</dependency>

And properties:

		<adwords.version>3.10.0</adwords.version>
		<google-content-api.version>v2-rev105-1.23.0</google-content-api.version>

**Comment by jradcliff** [comment]
Hi Peter,

Thanks for sharing your pom changes to work around this. Given the time of year, I'm going to hold off on releasing any changes to the library. However, I do plan to upgrade the dependency as you suggested in January 2018, provided the upgrade doesn't cause any additional issues (e.g., doesn't break any other dependencies).

Cheers,
Josh, AdWords API Team

**Comment by jradcliff** [comment]
Hi,

A quick update: we had a few items we wanted to roll out along with this fix, so I decided to hold off on a January release. I plan to include the fix for this issue in an upcoming release next week.

Thanks,
Josh, AdWords API Team

**Comment by jradcliff** [comment]
Fixed with release [3.11.0](https://github.com/googleads/googleads-java-lib/releases/tag/3.11.0).
