### ISSUE TITLE
Why there is no non-parameterized constructor for certain classes

### ISSUE THREAD

**Issue by Padmahas** [googleads/googleads-java-lib#134]
Hello,

We noticed some classes doesn't have non-parameterized constructor such as
1. com.google.api.ads.dfp.axis.v201708.GoalType;
2. com.google.api.ads.dfp.axis.v201708.UnitType;
3. [TimeUnit](https://developers.google.com/doubleclick-publishers/docs/reference/v201711/LineItemService.TimeUnit)
etc

In some situation, I need to copy GoalType object to custom GoalType object using BeanUtils.copyProperties.
Since GoalType doesn't have non-parameterized constructor, I need to initialize GoalType object to null.
GoalType goalTy = null;

If I try to copy using BeanUtils to this null object, it will throw exception. "Target must not be null".
BeanUtils.copyProperties(lineItemObj.getPrimaryGoal().getGoalType(), goalTy);

Is there is any specific reason for not to provide non-parameterized constructor?

Thank you.

**Comment by christopherseeley** [comment]
Yes, these are meant to represent enumerations and should not be null. However, the [axis stub](https://github.com/googleads/googleads-java-lib/blob/3.12.0/modules/dfp_axis/src/main/java/com/google/api/ads/dfp/axis/v201802/GoalType.java#L38) generation doesn't actually create these as Java enums, so the code is a little messy.

An alternative might be using the dfp_appengine module instead, which has properly generated [Java enums](https://github.com/googleads/googleads-java-lib/blob/3.12.0/modules/dfp_appengine/src/main/java/com/google/api/ads/dfp/jaxws/v201802/GoalType.java#L41).

If you're set on using the axis library, then you probably need to register a custom Converter.
