### ISSUE TITLE
Question: AdWords and DFP client library for Java will soon require Java 8+

### ISSUE THREAD

**Issue by planser** [googleads/googleads-java-lib#137]
Just to be sure that I understood this correctly:

According to https://ads-developers.googleblog.com/2018/03/adwords-and-dfp-client-library-for-java.html Starting on July 1, 2018, all releases of the Google Ads API Client Library for Java will only be compatible with Java 8 (1.8) and higher.

Will the upcoming version v201806 (https://ads-developers.googleblog.com/2017/10/adwords-api-release-and-sunset-schedule.html) be compatible with Java versions < 8?

**Comment by jradcliff** [comment]
Hi,

Good question! The version of the library that we'll release for v201806 *will be compatible with Java 7*. That's actually why we chose July as the cutoff date. :smiley:  We didn't want the change to Java 8 to prevent anyone from upgrading to v201806 of the AdWords API.

Cheers,
Josh, AdWords API Team
