### ISSUE TITLE
Custom config

### ISSUE THREAD

**Issue by kostap13** [googleads/googleads-java-lib#139]
I'm trying to create Credential with custom Configuration.
``` java
       Credential oAuth2Credential =
                new OfflineCredentials.Builder()
                        .forApi(OfflineCredentials.Api.ADWORDS)
                        .from(configuration)
                        .build()
                        .generateCredential();
```

1) Cause: com.google.api.ads.common.lib.exception.ValidationException: Client ID must be set.
``` java
        configuration.addProperty("refreshToken", getRefreshToken());
        configuration.addProperty("clientId", getClientId());
        configuration.addProperty("clientSecret", getClientSecret());
        configuration.addProperty("clientCustomerId", getClientCustomerId());
        configuration.addProperty("developerToken", getDeveloperToken());
        configuration.addProperty("isPartialFailure", getIsPartialFailure());
```

2) Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Request processing failed; nested exception is com.google.api.ads.common.lib.conf.ConfigurationLoadException: Encountered a problem reading the provided configuration file "ads.properties"!] with root cause

org.apache.commons.configuration.ConfigurationException: Cannot locate configuration source ads.properties
``` java
        configuration.addProperty("api.adwords.refreshToken", getRefreshToken());
        configuration.addProperty("api.adwords.clientId", getClientId());
        configuration.addProperty("api.adwords.clientSecret", getClientSecret());
        configuration.addProperty("api.adwords.clientCustomerId", getClientCustomerId());
        configuration.addProperty("api.adwords.developerToken", getDeveloperToken());
        configuration.addProperty("api.adwords.isPartialFailure", getIsPartialFailure());
```

Thanks

**Comment by jradcliff** [comment]
Hi,

Instead of creating a `Configuration` object, I recommend using the builders for `Credential` and `AdWordsSession` as shown in this example:

https://github.com/googleads/googleads-java-lib/blob/master/examples/adwords_axis/src/main/java/adwords/axis/auth/CreateAdWordsSessionWithoutPropertiesFile.java#L47

A big advantage to the builders is that you won't have to set properties using keys, but instead can just call the corresponding builder methods such as `withClientSecrets`, `withDeveloperToken`, etc.

Would that approach work for you?

Thanks,
Josh, AdWords API Team

**Comment by kostap13** [comment]
Thank you!
But I have same error:
``` java
Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Request processing failed; nested exception is com.google.api.ads.common.lib.conf.ConfigurationLoadException: Encountered a problem reading the provided configuration file "ads.properties"!] with root cause

org.apache.commons.configuration.ConfigurationException: Cannot locate configuration source ads.properties
```

``` java

import com.google.api.ads.adwords.lib.client.AdWordsSession;
import com.google.api.ads.common.lib.auth.OfflineCredentials;
import com.google.api.ads.common.lib.conf.ConfigurationLoadException;
import com.google.api.ads.common.lib.exception.OAuthException;
import com.google.api.ads.common.lib.exception.ValidationException;
import com.google.api.client.auth.oauth2.Credential;
import lombok.extern.slf4j.Slf4j;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.context.annotation.Scope;
import org.springframework.stereotype.Service;

@Service
@Slf4j
public class AuthService {

    @Autowired
    private AdwordsProperties adwordsProperties;

    public AdWordsSession getSession() throws ConfigurationLoadException, ValidationException, OAuthException {
        Credential credential = new OfflineCredentials.Builder()
                .forApi(OfflineCredentials.Api.ADWORDS)
                .withClientSecrets(adwordsProperties.getClientId(), adwordsProperties.getClientSecret())
                .withRefreshToken(adwordsProperties.getRefreshToken())
                .build()
                .generateCredential();
        credential.getExpiresInSeconds();
        return new AdWordsSession.Builder().fromFile().withOAuth2Credential(credential).build();
    }
}

```

**Comment by kostap13** [comment]
@jradcliff  Thank you!

**Comment by jradcliff** [comment]
Hi,

You're welcome! :smiley:

If that approach worked for you, could you close out the issue? If you're still having trouble, please let me know and I'll be happy to help.

Cheers,
Josh, AdWords API Team

**Comment by kostap13** [comment]
@jradcliff 
It seems that there is bug at example. It doesn't works without:
``` java
.withClientCustomerId(getClientCustomerId())
```

**Comment by jradcliff** [comment]
Hi,

Sorry, that may be a bit confusing. The example specifically calls the `getCustomers` method of `CustomerService` since the idea is that it will show you which customers (`clientCustomerIds`) your OAuth credentials can access. That is actually the _only_ call that lets you skip the `clientCustomerId`.

For any other service, you will have to also set the `clientCustomerId`. I'll make a note to add a comment to the example to clarify that point.

Cheers,
Josh, AdWords API Team
