### ISSUE TITLE
GetKeywordIdeas(v201802)

### ISSUE THREAD

**Issue by SallyChen47** [googleads/googleads-java-lib#141]
Hi,

I am testing the TargetingIdeaPage and I use the example class 'GetKewordIdeas'(googleads-java-lib/examples/adwords_axis/src/main/java/adwords/axis/v201802/optimization/GetKeywordIdeas.java). When I only pass the SeedAdGroupIdSearchParameter , it will return the keywords suggestions that related to my ad group. When I only pass the RelatedToQuerySearchParameter, it will return the keyword suggestions that related to the given keyword, but when I pass my SeedAdGroupIdSearchParameter and the RelatedToQuerySearchParameter the result is the same as only passing the RelatedToQuerySearchParameter. I read the Google AdWords API Document (https://developers.google.com/adwords/api/docs/reference/v201802/TargetingIdeaService.TargetingIdeaSelector),  and I found that the adGroup's keywords would be used to generate new and related keywords when passing the SeedAdGroupIdSearchParameter. I would like to know what is the right result when passing the RelatedToQuerySearchParameter and SeedAdGroupIdSearchParameter. 

Thanks
Sally

**Comment by jradcliff** [comment]
Hi Sally,

Since your question is about the AdWords API itself and not specific to the client library, could you post this question to the AdWords API Forum?

https://groups.google.com/forum/#!forum/adwords-api

Thanks,
Josh, AdWords API Team
