### ISSUE TITLE
can not open link | 无法打开超链接

### ISSUE THREAD

**Issue by 429463267** [googleads/googleads-java-lib#152]
can not open link | 无法打开超链接

1-
——————————————————————————
![image](https://user-images.githubusercontent.com/12899262/44132634-76175866-a08d-11e8-9652-1a691b6a5e09.png)

![image](https://user-images.githubusercontent.com/12899262/44132637-798a01d8-a08d-11e8-9566-22b036dd6299.png)

2-
![image](https://user-images.githubusercontent.com/12899262/44132738-12dcfb6a-a08e-11e8-81ae-21645efa440c.png)

![image](https://user-images.githubusercontent.com/12899262/44132740-14adcbae-a08e-11e8-8b65-3ce742efb494.png)

__________________________
难道我的姿势有问题？

**Comment by jradcliff** [comment]
Hi,

Do you have an ad blocker installed, perhaps? I was able to open the JavaDoc link without issue.

I will remove the Google+ link, as we are no longer using that profile. Thanks for pointing that out.

Cheers,
Josh, AdWords API Team
