### ISSUE TITLE
No new version related to v201809 is tagged

### ISSUE THREAD

**Issue by srinivasgiduthuri** [googleads/googleads-java-lib#153]
There is no version tagged or released here which has v201809 which was released on Sep 18th, 2018. Could you please let me know when it can be tagged or released here?

**Comment by jradcliff** [comment]
Hi,

The updated library and examples for v201809 were released today as [version 4.1.0](https://github.com/googleads/googleads-java-lib/releases/tag/4.1.0). Note that it may take a few hours for the Maven central repository to publish the changes.

For each release, the AdWords API Team targets releasing the updated client libraries within 48 hours of the release announcement (please see the [end of the blog post announcing v201809](https://ads-developers.googleblog.com/2018/09/announcing-v201809-of-adwords-api.html)).

Thanks,
Josh, AdWords API Team
