### ISSUE TITLE
ApiError ADVERTISER_NOT_WHITELISTED_FOR_USING_UPLOADED_DATA while uploading customers

### ISSUE THREAD

**Issue by srinivasgiduthuri** [googleads/googleads-java-lib#157]
Hello all,

We are getting the following exception while uploading the customers to Google Ads.

Following is the request and response payloads.

[29 Oct 2018 19:26:48,103-requestInfoLogger:WARN:main] Request made: Service: AdwordsUserListService Method: mutate clientCustomerId: 133-941-2293 URL: https://adwords.google.com/api/adwords/rm/v201809/AdwordsUserListService Request ID: 0005795e70a3d8900a7ef18780075647 ResponseTime(ms): 264 OperationsCount: 1 IsFault: true FaultMessage: ApiException{applicationExceptionType=ApiException, errors=[UserListError{apiErrorType=UserListError, errorString=UserListError.ADVERTISER_NOT_WHITELISTED_FOR_USING_UPLOADED_DATA, fieldPath=operations[0].operand, fieldPathElements=[FieldPathElement{field=operations, index=0}, FieldPathElement{field=operand}], reason=USER_LIST_SERVICE_ERROR, trigger=}]}
[29 Oct 2018 19:26:48,271-soapXmlLogger:INFO:main] SOAP request:
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
    <soapenv:Header>
        <ns1:RequestHeader xmlns:ns1="https://adwords.google.com/api/adwords/rm/v201809" soapenv:mustUnderstand="0">
            <ns2:clientCustomerId xmlns:ns2="https://adwords.google.com/api/adwords/cm/v201809">133-941-2293</ns2:clientCustomerId>
            <ns3:developerToken xmlns:ns3="https://adwords.google.com/api/adwords/cm/v201809">REDACTED</ns3:developerToken>
            <ns4:userAgent xmlns:ns4="https://adwords.google.com/api/adwords/cm/v201809">PMM Test Account (AwApi-Java, AdWords-Axis/4.1.0, Common-Java/4.1.0, Axis/1.4, Java/1.8.0_131, maven)</ns4:userAgent>
            <ns5:validateOnly xmlns:ns5="https://adwords.google.com/api/adwords/cm/v201809">false</ns5:validateOnly>
            <ns6:partialFailure xmlns:ns6="https://adwords.google.com/api/adwords/cm/v201809">false</ns6:partialFailure>
        </ns1:RequestHeader>
    </soapenv:Header>
    <soapenv:Body>
        <mutate xmlns="https://adwords.google.com/api/adwords/rm/v201809">
            <operations>
                <ns7:operator xmlns:ns7="https://adwords.google.com/api/adwords/cm/v201809">ADD</ns7:operator>
                <operand xmlns:ns8="https://adwords.google.com/api/adwords/rm/v201809" xsi:type="ns8:CrmBasedUserList">
                    <ns8:name>1a211566-5f85-4f36-9251-ed6e741deb8f</ns8:name>
                    <ns8:description>1a211566-5f85-4f36-9251-ed6e741deb8f</ns8:description>
                    <ns8:status>OPEN</ns8:status>
                    <ns8:membershipLifeSpan>10000</ns8:membershipLifeSpan>
                    <ns8:UserList.Type>CRM_BASED</ns8:UserList.Type>
                    <ns8:uploadKeyType>CONTACT_INFO</ns8:uploadKeyType>
                </operand>
            </operations>
        </mutate>
    </soapenv:Body>
</soapenv:Envelope>

[29 Oct 2018 19:26:48,271-soapXmlLogger:INFO:main] SOAP response:
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<soap:Envelope xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/">
    <soap:Header>
        <ns2:ResponseHeader xmlns="https://adwords.google.com/api/adwords/cm/v201809" xmlns:ns2="https://adwords.google.com/api/adwords/rm/v201809">
            <requestId>0005795e70a3d8900a7ef18780075647</requestId>
            <serviceName>AdwordsUserListService</serviceName>
            <methodName>mutate</methodName>
            <operations>1</operations>
            <responseTime>264</responseTime>
        </ns2:ResponseHeader>
    </soap:Header>
    <soap:Body>
        <soap:Fault>
            <faultcode>soap:Client</faultcode>
            <faultstring>[UserListError.ADVERTISER_NOT_WHITELISTED_FOR_USING_UPLOADED_DATA @ operations[0].operand]</faultstring>
            <detail>
                <ns2:ApiExceptionFault xmlns="https://adwords.google.com/api/adwords/cm/v201809" xmlns:ns2="https://adwords.google.com/api/adwords/rm/v201809">
                    <message>[UserListError.ADVERTISER_NOT_WHITELISTED_FOR_USING_UPLOADED_DATA @ operations[0].operand]</message>
                    <ApplicationException.Type>ApiException</ApplicationException.Type>
                    <errors xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:type="ns2:UserListError">
                        <fieldPath>operations[0].operand</fieldPath>
                        <fieldPathElements>
                            <field>operations</field>
                            <index>0</index>
                        </fieldPathElements>
                        <fieldPathElements>
                            <field>operand</field>
                        </fieldPathElements>
                        <trigger/>
                        <errorString>UserListError.ADVERTISER_NOT_WHITELISTED_FOR_USING_UPLOADED_DATA</errorString>
                        <ApiError.Type>UserListError</ApiError.Type>
                        <ns2:reason>USER_LIST_SERVICE_ERROR</ns2:reason>
                    </errors>
                </ns2:ApiExceptionFault>
            </detail>
        </soap:Fault>
    </soap:Body>
</soap:Envelope>

Request failed due to ApiException. Underlying ApiErrors:
  Error 0: UserListError{apiErrorType=UserListError, errorString=UserListError.ADVERTISER_NOT_WHITELISTED_FOR_USING_UPLOADED_DATA, fieldPath=operations[0].operand, fieldPathElements=[FieldPathElement{field=operations, index=0}, FieldPathElement{field=operand}], reason=USER_LIST_SERVICE_ERROR, trigger=}

**Comment by nwbirnie** [comment]
Hello, thanks for reporting this issue. We recently rolled out a whitelist for API access to customer match user lists. Please reach out on the [AdWords API Forum](https://groups.google.com/forum/#!forum/adwords-api) for assistance in getting whitelisted.
