### ISSUE TITLE
Google API Error

### ISSUE THREAD

**Issue by kdotzenrod517** [googleads/googleads-java-lib#160]
We’re receiving an exception in one of our services, and we are wondering if this is an authentication issue or a dependency error. Pasting the error below:

`Unable to provision, see the following errors: 1) null returned by binding at com.google.api.ads.common.lib.factory.FactoryModule$AdsServiceClientFactoryInterface.create() but parameter 2 of com.google.api.ads.dfp.lib.client.DfpServiceClient.() is not @Nullable while locating com.google.api.ads.dfp.lib.client.DfpSession annotated with @com.google.inject.assistedinject.Assisted(value=adsSession) for parameter 2 at com.google.api.ads.dfp.lib.client.DfpServiceClient.(DfpServiceClient.java:56) while locating com.google.api.ads.dfp.lib.client.DfpServiceClient annotated with @com.google.inject.internal.UniqueAnnotations$Internal(value=1) 1 error`

Any insight into this error would be greatly appreciated.

**Comment by nwbirnie** [comment]
Hey, we have recently rebranded the DFP library to match the new Google Ad Manager product. Its likely that you have both the DFP and Ad Manager dependencies coexisting in your project. Please check your project for conflicting versions of the `com.google.api-ads` modules, these should all be on the same version.

**Comment by kdotzenrod517** [comment]
hey! this is the dependency tree of the only instance of `com.google.api-ads` in the project. It looks like they are all on the same version:

|    \--- com.google.api-ads:ads-lib-axis:3.16.0
|         +--- com.google.api-ads:ads-lib:3.16.0 (*)
|         +--- commons-discovery:commons-discovery:0.4
|         |    \--- commons-logging:commons-logging:1.0.4 -> 1.2
|         +--- com.google.http-client:google-http-client:1.23.0 (*)
|         +--- javax.xml:jaxrpc-api:1.1
|         +--- org.apache.axis:axis:1.4
|         \--- wsdl4j:wsdl4j:1.6.2 -> 1.6.3

**Comment by nwbirnie** [comment]
The dependency on `ads-lib-axis` is wrong. If you're using AdWords API you should change this to `adwords-axis` and similarly, for DFP to `dfp-axis`.

**Comment by kdotzenrod517** [comment]
Something like this?

`compile('com.google.api-ads:dfp-axis:3.16.0')`

**Comment by nwbirnie** [comment]
Yes, and looking at the dependency tree you will have to add `com.google.api-ads:ads-lib:3.16.0` again, since this was being included transitively.

**Comment by kdotzenrod517** [comment]
+--- com.google.api-ads:dfp-axis:3.16.0
|    +--- com.google.api-ads:ads-lib:3.16.0
|    |    +--- com.google.guava:guava:20.0
|    |    +--- com.google.inject:guice:4.0
|    |    |    +--- javax.inject:javax.inject:1
|    |    |    +--- aopalliance:aopalliance:1.0
|    |    |    \--- com.google.guava:guava:16.0.1 -> 20.0
|    |    +--- com.google.inject.extensions:guice-assistedinject:4.0
|    |    |    \--- com.google.inject:guice:4.0 (*)
|    |    +--- com.google.inject.extensions:guice-multibindings:4.0
|    |    |    \--- com.google.inject:guice:4.0 (*)
|    |    +--- commons-beanutils:commons-beanutils:1.9.2 -> 1.9.3
|    |    |    \--- commons-logging:commons-logging:1.2
|    |    +--- commons-configuration:commons-configuration:1.10
|    |    |    +--- commons-lang:commons-lang:2.6
|    |    |    \--- commons-logging:commons-logging:1.1.1 -> 1.2
|    |    +--- commons-collections:commons-collections:3.2.2
|    |    +--- commons-lang:commons-lang:2.6
|    |    +--- net.sf.opencsv:opencsv:1.8 -> 2.3
|    |    +--- org.slf4j:slf4j-api:1.7.7 -> 1.7.22
|    |    +--- joda-time:joda-time:2.8.2 -> 2.9.7
|    |    +--- com.google.api-client:google-api-client:1.23.0
|    |    |    +--- com.google.oauth-client:google-oauth-client:1.23.0
|    |    |    |    +--- com.google.http-client:google-http-client:1.23.0
|    |    |    |    |    +--- com.google.code.findbugs:jsr305:1.3.9 -> 3.0.1
|    |    |    |    |    \--- org.apache.httpcomponents:httpclient:4.0.1 -> 4.5.2
|    |    |    |    |         +--- org.apache.httpcomponents:httpcore:4.4.4 -> 4.4.6
|    |    |    |    |         +--- commons-logging:commons-logging:1.2
|    |    |    |    |         \--- commons-codec:commons-codec:1.9 -> 1.10
|    |    |    |    \--- com.google.code.findbugs:jsr305:1.3.9 -> 3.0.1
|    |    |    \--- com.google.http-client:google-http-client-jackson2:1.23.0
|    |    |         +--- com.google.http-client:google-http-client:1.23.0 (*)
|    |    |         \--- com.fasterxml.jackson.core:jackson-core:2.1.3 -> 2.8.6
|    |    +--- com.google.http-client:google-http-client-jackson2:1.23.0 (*)
|    |    \--- com.beust:jcommander:1.48
|    \--- com.google.api-ads:ads-lib-axis:3.16.0
|         +--- com.google.api-ads:ads-lib:3.16.0 (*)
|         +--- commons-discovery:commons-discovery:0.4
|         |    \--- commons-logging:commons-logging:1.0.4 -> 1.2
|         +--- com.google.http-client:google-http-client:1.23.0 (*)
|         +--- javax.xml:jaxrpc-api:1.1
|         +--- org.apache.axis:axis:1.4
|         \--- wsdl4j:wsdl4j:1.6.2 -> 1.6.3
+--- com.google.api-ads:ads-lib:3.16.0 (*)

**Comment by kdotzenrod517** [comment]
we are still experiencing this error, our Google dependencies are:

  compile('com.google.api-ads:ads-lib:3.16.0')
  compile('com.google.api-ads:dfp-axis:3.16.0'){
    exclude group: "com.google.guava", module:"guava"
    exclude group: "com.google.guava", module:"guava-jdk5"
  }
  compile ("com.google.cloud:google-cloud:0.26.0-alpha") {
    exclude group: "javax.servlet", module: "servlet-api"
    exclude group: "com.google.guava", module:"guava"
  }
  compile("com.google.code.gson:gson:2.8.2"){
    exclude group: "com.google.guava", module:"guava"
  }
  compile("com.google.apis:google-api-services-sheets:v4-rev469-1.22.0"){
    exclude group: "com.google.guava", module:"guava"
    exclude group: "com.google.guava", module:"guava-jdk5"
  }

Would any of these dependencies be conflicting?

**Comment by kdotzenrod517** [comment]
Any insight into this would be much appreciated, we are still receiving the error below and believe it has something to do with our dependencies:

Unable to provision, see the following errors: 1) null returned by binding at com.google.api.ads.common.lib.factory.FactoryModule$AdsServiceClientFactoryInterface.create() but parameter 2 of com.google.api.ads.dfp.lib.client.DfpServiceClient.() is not @Nullable while locating com.google.api.ads.dfp.lib.client.DfpSession annotated with @com.google.inject.assistedinject.Assisted(value=adsSession) for parameter 2 at com.google.api.ads.dfp.lib.client.DfpServiceClient.(DfpServiceClient.java:56) while locating com.google.api.ads.dfp.lib.client.DfpServiceClient annotated with @com.google.inject.internal.UniqueAnnotations$Internal(value=1) 1 error

**Comment by jradcliff** [comment]
Hi,

A few follow-up questions that will help with our investigation:

1. Do you encounter this error for *every* service, or only for a specific use case? If the latter, please let us know the use case that is not working as well as one that is.
2. Is there more of your stack trace that you could share, or a snippet of your code that's triggering this exception?

Thanks,
Josh

**Comment by kdotzenrod517** [comment]
We were able to resolve the issue. 

Thank you for your help!
