### ISSUE TITLE
Please update guice to support JDK9+

### ISSUE THREAD

**Issue by markusheiden** [googleads/googleads-java-lib#164]
Please update the guice dependency to support JDK9+.

WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by com.google.inject.internal.cglib.core.$ReflectUtils$2 (file:/Users/markus/.m2/repository/com/google/inject/guice/4.0/guice-4.0.jar) to method java.lang.ClassLoader.defineClass(java.lang.String,byte[],int,int,java.security.ProtectionDomain)
WARNING: Please consider reporting this to the maintainers of com.google.inject.internal.cglib.core.$ReflectUtils$2
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release

**Comment by nwbirnie** [comment]
Thanks for reporting this - JDK9+ support is indeed on our roadmap for this year. We were thinking that this is only a warning though, and while annoying, it doesn't actually break the library at runtime. Could you confirm if this is the case?

**Comment by markusheiden** [comment]
Yes, it works, even with JDK 11.

**Comment by christopherseeley** [comment]
We updated to guice 4.2 which has JDK9 support in v.5.0
https://github.com/googleads/googleads-java-lib/releases/tag/4.5.0
