### ISSUE TITLE
Question - Ad Manager Reporting Api

### ISSUE THREAD

**Issue by kdotzenrod517** [googleads/googleads-java-lib#165]
Hello, 

Is there a way to stream an Ad Manager reports contents using Report Downloader utilities like there is for AdWords? I found this [documentation](https://github.com/googleads/googleads-java-lib/wiki/ReportDownloader-utilities), but it seems outdated. We are trying to pull in a years worth of historical data. 

Thanks

**Comment by jradcliff** [comment]
Hi,

I updated the documentation you referenced. Thanks for pointing out that it was outdated!

Please see the [section at the bottom of that page](https://github.com/googleads/googleads-java-lib/wiki/ReportDownloader-utilities#dfp-2) under "Process the report contents as a stream".

If that doesn't clear things up, feel free to reopen this issue with further questions.

Cheers,
Josh, AdWords API Team
