### ISSUE TITLE
ADM API SoapPacker AttributeError

### ISSUE THREAD

**Issue by bry8** [googleads/googleads-java-lib#167]
I upgraded the python library googleads, but get an error while making a request:

# Import the library.
from googleads import ad_manager

# Initialize a client object, by default uses the credentials in ~/googleads.yaml.
client = ad_manager.AdManagerClient.LoadFromStorage()

# Initialize a service.
network_service = client.GetService('NetworkService', version='v201811')

# Make a request.
current_network = network_service.getCurrentNetwork()

print( 'Found network %s (%s)!' % (current_network['displayName'],
                                  current_network['networkCode'])
    )

--> 396 class _AdManagerPacker(googleads.common.SoapPacker):
    397   """A utility applying customized packing logic for Ad Manager."""
    398 

AttributeError: module 'googleads.common' has no attribute 'SoapPacker'

**Comment by nwbirnie** [comment]
Thanks for reporting the issue, however this is the issue tracker for the Java library. Would you kindly reopen this on the [Python library](https://github.com/googleads/googleads-python-lib) please.
