### ISSUE TITLE
account-key.json path problem

### ISSUE THREAD

**Issue by tryandcatch** [googleads/googleads-java-lib#172]
Hello guys.
Need help 
When I run project(SpringBoot 2.1.3) using `java -jar PROJECT_NAME.jar`,**it occurs problems,but it run correctly in IDEA.**
Exception:
```
com.google.api.ads.common.lib.exception.OAuthException: Service account key file could not be loaded.

   at com.google.api.ads.common.lib.auth.OfflineCredentials.generateCredentialFromKeyFile(OfflineCredentials.java:272)
        
   at com.google.api.ads.common.lib.auth.OfflineCredentials.generateCredential(OfflineCredentials.java:232)
....
Caused by: java.io.FileNotFoundException: account-key.json (No such file or directory)
        at java.io.FileInputStream.open0(Native Method)
        at java.io.FileInputStream.open(FileInputStream.java:195)
        at java.io.FileInputStream.<init>(FileInputStream.java:138)
        at com.google.common.io.Files$FileByteSource.openStream(Files.java:120)
        at com.google.common.io.Files$FileByteSource.openStream(Files.java:110)
....
```
googleads-java-lib is `4.4.0`
code:

```
Credential credential = new OfflineCredentials.Builder()
                .forApi(OfflineCredentials.Api.AD_MANAGER)
                .fromFile()
                .build()
                .generateCredential();
```
file position:
![image](https://user-images.githubusercontent.com/12490603/56028127-0dae4a80-5d4a-11e9-9181-123773f01835.png)

ads.properties:
```
api.admanager.applicationName=dfp-demo
api.admanager.networkCode=NET_WORK_CODE
api.admanager.jsonKeyFilePath=src/main/resources/account-key.json
```

Thanks

**Comment by KenMills** [comment]
What was the resolution? I'm running into the same issue (runs in ide, but key file not found when I deploy).

**Comment by OlegMeditskiy** [comment]
I have the same problem. What's resolution?

**Comment by jradcliff** [comment]
It appears that the `OfflineCredentials` interprets the value of `api.admanager.jsonKeyFilePath` as a path in your *file system*, not on the class path. If you want to use a resource from your classpath, you could do something like this using Guava's [Resources utility](https://guava.dev/releases/snapshot/api/docs/com/google/common/io/Resources.html#getResource(java.lang.String)):

```
Credential credential = new OfflineCredentials.Builder()
                .forApi(OfflineCredentials.Api.AD_MANAGER)
                .withJsonKeyFilePath(
                     new File(
                         Resources.getResource("/src/main/resources/account-key.json").toURI()
                     )
                )
                .build()
                .generateCredential();
```

(caveat: I'm writing this off the top of my head, so please forgive typos)

Another option would be to place your `account-key.json` file in a specific location (not in the classpath) on your server, and then update `ads.properties` on the server to point `api.admanager.jsonKeyFilePath` to the *complete* path of that file.

Thanks,
Josh
