### ISSUE TITLE
How should I set my campaign’s goals in the adwords api

### ISSUE THREAD

**Issue by lyingfromyou** [googleads/googleads-java-lib#177]
![image](https://user-images.githubusercontent.com/24619864/61016100-09351480-a3c1-11e9-86fb-002ec6986e3f.png)

**Comment by nwbirnie** [comment]
Hey, the campaign goal is a UI only setting - it's effectively a theme which alters the options presented during CM flows. There's no direct impact on a campaign's performance by setting this - it's the bidding, targeting, quality score etc. which drives performance.
