### ISSUE TITLE
Failed to create OAuth credentials. Check OAuth settings in the ads.properties file. Exception: com.google.api.ads.common.lib.exception.OAuthException: Credential could not be refreshed.

### ISSUE THREAD

**Issue by thakorji007** [googleads/googleads-java-lib#179]
Hello to all 
currently i am working on one project and i am integrating **google adwords api** in that project , but after getting refresh token when i try to get Campaign then it give me below type of exception 

here is the exception

### Failed to create OAuth credentials. Check OAuth settings in the ads.properties file. Exception: com.google.api.ads.common.lib.exception.OAuthException: Credential could not be refreshed.

i don't know how to solve it , can you please help me to solve this type of exception ?

**Comment by nwbirnie** [comment]
It's likely that the client ID and secret were not used to generate the refresh token in the first instance. Can you try recreating the refresh token by running the script [here](https://github.com/googleads/googleads-java-lib/blob/master/examples/adwords_axis/src/main/java/adwords/axis/auth/GetRefreshToken.java) please? If that doesn't fix the problem, please paste the full stack trace, including any causes.

**Comment by thakorji007** [comment]
Yes , i had been using  the old client id to generate the refresh token, now it is solved! Thanks for your response and support!

**Comment by thakorji007** [comment]
but it give one exception 
and here is that exception message :: 

**Could not initialize class com.google.api.ads.adwords.axis.factory.AdWordsServices**

and here is the exception

[**java.lang.NoClassDefFoundError: Could not initialize class com.google.api.ads.adwords.axis.factory.AdWordsServices**](https://github.com/googleads/googleads-java-lib/issues/178)

**Comment by nwbirnie** [comment]
Yes I see. I followed up on the other issue, let's discuss over there.
