### ISSUE TITLE
Can the API set the language of the campaign?

### ISSUE THREAD

**Issue by lyingfromyou** [googleads/googleads-java-lib#182]
hey, Can the API set the language of the campaign?

**Comment by nwbirnie** [comment]
Hey, 

The Github page is for issues relating to the Java client library for AdWords API - for general questions on the API, please add a post on the [AdWords API forum](https://groups.google.com/forum/#!forum/adwords-api).

To answer your question, you can use [CampaignCriterionService](https://developers.google.com/adwords/api/docs/reference/v201809/CampaignCriterionService) to add a Language criterion to your campaign.
