### ISSUE TITLE
Please update google-api-client

### ISSUE THREAD

**Issue by markusheiden** [googleads/googleads-java-lib#183]
We are using AdWords together with Analytics. For the google-api-client dependency AdWords got stuck at 1.23.0 while Analytics does not provide any current version using that old google-api-client. Their current version only includes google-api-client 1.26.0+. May you please update the dependency to avoid version conflicts?

**Comment by christopherseeley** [comment]
Fixed in [v4.9.0](https://github.com/googleads/googleads-java-lib/releases/tag/4.9.0).
