### ISSUE TITLE
AddGmailAdd.java APIException

### ISSUE THREAD

**Issue by jasperan** [googleads/googleads-java-lib#187]
Hello, I need to create a GmailAd. However, when modifying the code example in:

https://github.com/googleads/googleads-java-lib/blob/967957cc4f6076514e3a7926fe653e4f1f7cc9c9/examples/adwords_axis/src/main/java/adwords/axis/v201809/advancedoperations/AddGmailAd.java

Adding my own AdGroupId, I get the following exception:

Request failed due to ApiException. Underlying ApiErrors:
  Error 0: NullError{apiErrorType=NullError, errorString=NullError.NULL_CONTENT, fieldPath=media[0].data, fieldPathElements=[FieldPathElement{field=media, index=0}, FieldPathElement{field=data}], reason=NULL_CONTENT, trigger=}

I have investigated about the NullError exception: https://developers.google.com/adwords/api/docs/reference/v201809/ReportDefinitionService.NullError

However the code example doesn't seem to have any issues (nothing seems to be null when printing it).

Appreciate any help at this point.

**Comment by nwbirnie** [comment]
Hey, since this isn't specific to the Java client, please ask on the [forum](https://groups.google.com/forum/#!forum/adwords-api) where our support team will take a look shortly. 

Best wishes,
Nick
