### ISSUE TITLE
Not Working on Linux

### ISSUE THREAD

**Issue by koshishrijal** [googleads/googleads-java-lib#191]
Hi! I am providing credentials in the constructor! Its working fine in windows machine but in linux It throiws this exception!

Failed to create OAuth credentials. Check OAuth settings in the ads.properties file. Exception: com.google.api.ads.common.lib.exception.OAuthException: Credential could not be refreshed.

**Comment by nwbirnie** [comment]
Can you verify that the same credentials are being passed to the constructor on both platforms please (e.g. using the debugger)?

**Comment by koshishrijal** [comment]
yeah! Intrestingly! Its the issue with out ubuntu server! Its working on all other servers except the one! Server settings are same though,but we are getting !
Exception: com.google.api.ads.common.lib.exception.OAuthException: Credential could not be refreshed.

**Comment by nwbirnie** [comment]
Could you try editing the ads.properties file on Linux (e.g. in vim) and inserting new line endings and saving again? I want to rule out the possibility of Windows line endings corrupting the input.

Also check the ads.properties file for any special characters, particularly around the lines for OAuth configuration.
