### ISSUE TITLE
Example to get companey page by date

### ISSUE THREAD

**Issue by MallikarjunHt** [googleads/googleads-java-lib#216]
i have an issue while fetching companey page for pertiular page 
hear is the code snippet i use 
```java
StatementBuilder statementBuilder = new StatementBuilder()
                .where( " lastModifiedDateTime>='" + startDate.split("T")[0].concat("T00:00:00") +"' and " +
                "lastModifiedDateTime<='" + endDate.split("T")[0].concat("T23:59:59") + "' ");
```
i have data runniong foe single day it takes entire day and the quarrey fails with time out and the data i have recived is of incomplete

any sujession is welcome

**Comment by nwbirnie** [comment]
Hey, it looks like this is for ad manager - @christopherseeley can you advise?

I don't work on Ad Manager, but it looks like you may be trying to download a huge amount of data. It might be worth trying to request smaller batches, e.g. by requesting one day of data at a time.

**Comment by MallikarjunHt** [comment]
since i was using localDateTime i had an error and now i have made use of correct dateTime so i am getting data
