### ISSUE TITLE
Java: Compilation error: internal java compiler error

### ISSUE THREAD

**Issue by hommedahl15** [googleads/googleads-java-lib#222]
I just cloned this library and tried to run the GetCampaigns.java file.

After running, it returned an error that said "Compilation failed: internal java compiler error". 

I'm using Oracle OpenJDK 16.0.1

Any idea why this is happening? 

![internal java compiler error](https://user-images.githubusercontent.com/85193400/120377627-ff816680-c2e2-11eb-8cc0-57d6437b2006.png)

**Comment by nwbirnie** [comment]
A common issue is that the compiler requires quite a lot of memory to complete. Can you try increasing this setting in the IDE?

![image](https://user-images.githubusercontent.com/410275/120478084-6155d500-c3a4-11eb-9100-83af0e7d6ced.png)

**Comment by nwbirnie** [comment]
Failing that, please could you post the full stacktrace from the compiler, thanks.

**Comment by hommedahl15** [comment]
This worked. Thank you!!
