### ISSUE TITLE
Java: package com.google.ads.googleads.test does not exist

### ISSUE THREAD

**Issue by hommedahl15** [googleads/googleads-java-lib#223]
I tried to run the GetCampaigns.java file and got this error. "Java: package com.google.ads.googleads.test does not exist"

![image](https://user-images.githubusercontent.com/85193400/121227345-0fec9080-c851-11eb-920d-4e501ee3bae1.png)

Any idea why this is happening?

**Comment by jradcliff** [comment]
The library uses annotation processors during the build. If using IntelliJ, you can make sure annotation processing is enabled by going to **Build, Execution, Deployment -> Compiler -> Annotation processors**, then selecting **google-ads**, and checking **Enable annotation processing**. That package isn't generated by annotation processors, but if they don't run it could cause other build steps to fail.

Thanks

**Comment by hommedahl15** [comment]
I enabled the annotation process, but it's still returning the same error "java: package com.google.ads.googleads.test does not exist" after running the GetCampaigns.java file.

It opens the ReflectionFieldAccessorTest.java file after running GetCampagins.java. Note that I have not done anything else with this library. I've cloned it & enabled annotation processing. Are there any other necessary steps that I have not completed? Thank you for the help!

![image](https://user-images.githubusercontent.com/85193400/121261109-e09d4a00-c877-11eb-8865-300673cb808f.png)


![image](https://user-images.githubusercontent.com/85193400/121261026-be0b3100-c877-11eb-8af6-4d903306c557.png)

**Comment by jradcliff** [comment]
Hi,

I was able to reproduce the issue you were having on a newly created project. What fixed it for me was to manually run the `test` phase in IntelliJ.

![maven](https://user-images.githubusercontent.com/6033175/121434668-a9986880-c94b-11eb-833b-4dc443ffea18.png)

That forced the `generate-test-sources` phase to run, which is the phase that produces the missing package.

Note that I had to restart IntelliJ after running that phase.

Thanks,
Josh

P.S. For any future issues with the [google-ads-java project](https://github.com/googleads/google-ads-java), please use that project's issue tracker at https://github.com/googleads/google-ads-java/issues. This project (`googleads-java-lib`) is for the previous API.
