### ISSUE TITLE
Query regarding Adwords jars existing post sunset

### ISSUE THREAD

**Issue by saurabhsumanbbsr** [googleads/googleads-java-lib#232]
Hi Team,
As Adwords API is going to sunset on 27th April 2022, can you please  suggest if the Adwords JARs  and Ads API jars will co-exist post   27th April 2022. To be noted: we will be not be making any Adwords call as they will be failing post 27th April but need Adwords jar to avoid any build issues.

**Comment by jradcliff** [comment]
Hi,

AdWords API jars that are published to the Maven central repository will continue to exist there. We currently do not have any plans to "unpublish" those. Does that address your concern?

Thanks,
Josh, Google Ads API Team

**Comment by saurabhsumanbbsr** [comment]
Thank you for your response
