### ISSUE TITLE
Query regarding setting keywordMinActivationBid  and KewyordBid

### ISSUE THREAD

**Issue by saurabhsumanbbsr** [googleads/googleads-java-lib#233]
We are using AdGroupCriterion  ,we need keywordMinActivationBid and KeywordBid  attribute to be set.

Earlier in Adwords API we used to set the  keywordMinActivationBid as below where x is the instance of  BiddableAdGroupCriterion:

entry.setKeywordMinActivationBid(toMoney(x.getFirstPageCpc()));

So what is the  replacment for the  FirstPageCPC  in Google Ads API   for setting keywordMinActivationBid  using the AdGroupCriterion class.

In Adwords API, For Keyword entry we used to populate the KeywordBid as below:

entry.setKeywordBid(toMoney(((CpcBid)x.getBiddingStrategyConfiguration().getBids(0)).getBid()));  // x is the instance of BiddableAdGroupCriterion

Can you suggest the replacement for the same in Ads API.

**Comment by jradcliff** [comment]
Hi,

There aren't any attributes in the AdWords API named `keywordMinActivationBid` or `KeywordBid`, but if you're looking for the CPC bid of an ad group criterion in the Google Ads API, you can get and set that via the `cpc_bid_micros` field of [`AdGroupCriterion`](https://developers.google.com/google-ads/api/reference/rpc/v10/AdGroupCriterion#cpc_bid_micros).

Note that `cpc_bid_micros` will only be populated if you actually overrode the bid at the criterion level. If you want to retrieve the *effective* CPC bid, you can use `effective_cpc_bid_micros`. You can determine if the bid is from the strategy, campaign, or keyword level by checking the `effective_cpc_bid_source`.

Thanks,
Josh
