### ISSUE TITLE
'java.lang.NoClassDefFoundError: com/google/protobuf/ServiceException' 

### ISSUE THREAD

**Issue by bhatnagarA8884** [googleads/googleads-java-lib#235]
After adding the following dependency, I am getting error 'java.lang.NoClassDefFoundError: com/google/protobuf/ServiceException' which was not the case earlier when I was following 'ads-lib' and 'adwords-axis'.

<dependency>
 <groupId>com.google.api-ads</groupId>
 <artifactId>google-ads</artifactId>
 <version>17.0.1</version>
</dependency>

**Comment by jradcliff** [comment]
Hi,

Could you open this issue under the issues list for the google-ads-java library instead?

https://github.com/googleads/google-ads-java/issues

Also, please take a look at similar issues in that library like https://github.com/googleads/google-ads-java/issues/397. Other users have resolved those issues by inspecting and fixing their dependencies.

Thanks,
Josh

**Comment by bhatnagarA8884** [comment]
Ok, I have opened it in the forum you suggested i.e. https://github.com/googleads/google-ads-java/issues/603
