### ISSUE TITLE
EntityLimitReachedError.ENTITY_LIMIT_REACHED | Do I need a new Sandbox?

### ISSUE THREAD

**Issue by yusufyilmazfr** [googleads/googleads-java-lib#242]
Hello team!

I've been using Google Ad Manager Sandbox  for several months. In several days, my tests are not passed so I've checked my tests then I've realized Google Ads client  has thrown an exception that was `EntityLimitReachedError.ENTITY_LIMIT_REACHED`. 

In `Test vs. Production` page, it was written like:

Test networks are limited in the following ways:
- Test networks are limited to 10,000 objects per entity type.

I think this exception is thrown because of there are ~10,000 creatives in my Sandbox. I am not able to delete Creatives, Google API just provides deleting `LineItemCreativeAssociation` but it is just relationship.

To be honest If i have to generate a new Sandbox environment, It will be difficult to prepare Sandbox with; Key-Values, Native Creatives, Creative Templates, etc. Are there any effective ways to handle this problem or do I need a new Sandbox environment?

Thanks,

**Comment by christopherseeley** [comment]
You can either create a new sandbox or attempt to reuse existing creatives. Unfortunately those are the only two options at this time.
