### ISSUE TITLE
Not able to get v12 resources/services  with latest maven dependency

### ISSUE THREAD

**Issue by saurabhsumanbbsr** [googleads/googleads-java-lib#244]
Hi Team,
  I am using Java client library for Google Ads API . But while migrating from v10 to v12, I am not getting  resources  and services related to v12. Latest I can get is v11.

e.g. can not resolve com.google.ads.googleads.v12.resources.Campaign.

Maven dependency added:
	`<dependency>
		<groupId>com.google.api-ads</groupId>
		<artifactId>google-ads</artifactId>
		<version>21.0.0</version>
	</dependency>`
Please suggest.

**Comment by jradcliff** [comment]
Hi,

We're working on the library updates for v12 and I am aiming to have a release out by the end of this week.

Thanks,
Josh, Google Ads API Team

**Comment by saurabhsumanbbsr** [comment]
Hi Josh,
  Any further updates on v12 lib. 

Thanks,
Saurabh

**Comment by jradcliff** [comment]
Hi,

We release [22.0.0](https://github.com/googleads/google-ads-java/releases/tag/22.0.0) yesterday. That version includes support for versions v10 through v12.

Thanks
