### ISSUE TITLE
io.grpc.NameResolver$Args$Builder.setOverrideAuthority(Ljava/lang/String;)Lio/grpc/NameResolver$Args$Builder;

### ISSUE THREAD

**Issue by huan-ds** [googleads/googleads-java-lib#247]
Hi,

I am currently deploying Google Ads v12 and facing an issue while sending requests to v12 to create Google Bulk Job Service. The error log looks like this:

```
io.grpc.NameResolver$Args$Builder.setOverrideAuthority(Ljava/lang/String;)Lio/grpc/NameResolver$Args$Builder;
```
I attached the error stack trace: 

[GoogleBulkJob_errorlog.zip](https://github.com/googleads/google-ads-java/files/10348348/GoogleBulkJob_errorlog.zip)

Please kindly advice what could cause this issue.

Thanks, 
Huan

**Comment by christopherseeley** [comment]
Hello, this library is for the Ad Manager SOAP API. For the Google Ads API, use this repo:
https://github.com/googleads/google-ads-java/issues
