### ISSUE TITLE
Provide access to SOAP Response Headers

### ISSUE THREAD

**Issue by arogal** [googleads/googleads-java-lib#3]
We should provide a mechanism to gain access to the SOAP response headers.  Ideally, this would expose the values in the last request made for a given service stub.
Nov 29, 2012 Delete comment
 
To elaborate:
- This will allow developers to log the SOAP Request ID (useful when communicating with AdWords API support for debugging) without requiring SOAP Logging being enabled.
- Developers can check the unit cost to differentiate between a production account and a test account (CampaignService.get will cost 1 unit per campaign returned for production accounts, but test accounts will reflect zero units).
- Developers can programmatically track their own API unit consumption.

**Comment by jradcliff** [comment]
Since there is no longer a charge for using the AdWords API, and operation counts are not returned in SOAP headers anymore, this is no longer useful.
The `requestId` portion will be covered in [issue #4](https://github.com/googleads/googleads-java-lib/issues/4).

**Comment by jradcliff** [comment]
Correction to my previous update: operation counts **are** returned in SOAP responses, both for Basic and Standard access tokens. While working on the `requestId` issue, we'll look into adding operation counts to the summary log messages.
