### ISSUE TITLE
AdvertisingChannel null

### ISSUE THREAD

**Issue by davidbotella** [googleads/googleads-java-lib#35]
Here a sample code, using the utility extension. I'm trying to get the AdvertisingChannel value for each campaign, but I get a null value. I tried (firstly) to get ExtendedManagedCampaigns, but nothing is set. 

Is it a bug from the utility extension (so I'll post a feature request), from the account (not updated ? - don't think so), or something not handled by v201409 (open to shortlisted parters, as it can happend) ?

Thanks for your help !

Cheers

import com.google.api.ads.adwords.axis.utility.extension.ExtendedManagedCustomer;
import com.google.api.ads.adwords.axis.utility.extension.ExtendedMcc;
import com.google.api.ads.adwords.axis.v201409.cm.AdvertisingChannelType;
import com.google.api.ads.adwords.axis.v201409.cm.Campaign;
import com.google.api.ads.common.lib.conf.ConfigurationLoadException;
import com.google.api.ads.common.lib.exception.OAuthException;
import com.google.api.ads.common.lib.exception.ValidationException;
import java.rmi.RemoteException;
import java.util.List;

public class NewMain {

    /**
     * @param args the command line arguments
     */
    public static void main(String[] args) throws OAuthException, ValidationException, ConfigurationLoadException, RemoteException {
        
        ExtendedMcc mcc = ExtendedMcc.withOAuth2FromFile();
        ExtendedManagedCustomer customer = mcc.getExtendedManagedCustomer(someIdLong);
        List<Campaign> campaigns = customer.getCampaigns();
        
        for (Campaign c : campaigns) {
            AdvertisingChannelType channelType = c.getAdvertisingChannelType(); // null value;
            
            
        }
        
    }
    
}

**Comment by jradcliff** [comment]
Thanks for filing this issue - I think I found the problem. SelectorFields.Campaign is missing AdvertisingChannelType and AdvertisingChannelSubType:

https://github.com/googleads/googleads-java-lib/blob/bb4284b56387b13e5cbc6166adf382a6f6e48975/modules/adwords_axis_utility_extension/src/main/java/com/google/api/ads/adwords/axis/utility/extension/util/SelectorFields.java#L97

I'll work with the utility owner to get this fixed.

**Comment by jradcliff** [comment]
This is now fixed.

https://github.com/googleads/googleads-java-lib/blob/master/modules/adwords_axis_utility_extension/src/main/java/com/google/api/ads/adwords/axis/utility/extension/util/SelectorFields.java#L105
