### ISSUE TITLE
Shopping management - PHP libraries?

### ISSUE THREAD

**Issue by athen66** [googleads/googleads-java-lib#39]
Would love to see better shopping campaign / product partition management and examples in the PHP client libraries!

**Comment by dklimkin** [comment]
Please log this request under the PHP library instead:

  https://github.com/googleads/googleads-php-lib/issues/

**Comment by jradcliff** [comment]
Per the previous comment, please log this under the PHP library issues list.

https://github.com/googleads/googleads-php-lib/issues/
