### ISSUE TITLE
SelectorFields.java in Utility

### ISSUE THREAD

**Issue by davidbotella** [googleads/googleads-java-lib#40]
Hi,

The SelectorFields.java file hasn't been updated for 5 months, was already uncomplete and new features like upgradedUrl are not handled, leading the Utility to be obsolete. Is there any milestone planned to update it ? Any way we can contribute ?

Cheers,

- DB.

**Comment by jradcliff** [comment]
Hi DB,

We're working on bringing the extension utility up to date. I expect to have news on this in May, at which point I'll update this issue and let you know the plan.

Thanks

**Comment by jradcliff** [comment]
Resolved - please see my comments on [issue 47](https://github.com/googleads/googleads-java-lib/issues/47).
