### ISSUE TITLE
GCM cloud connection denied

### ISSUE THREAD

**Issue by freebird8x** [googleads/googleads-java-lib#42]
Hi

I'm trying to create a simple GCM Cloud Connection server with GAE to use for push notification on Android. I followed this example:

http://developer.android.com/google/gcm/ccs.html#smack

However I keep receiving the error: 
        "The following addresses failed: 'gcm.googleapis.com:5235' failed because java.net.SocketException: Permission denied: Attempt to access a blocked recipient without permission."
       
I'm using Smack 4.0.7. I have enabled "Google Cloud Messaging for Android" and also have enabled billing for the testing project, but it still doesn't work. The code always crashed at the point where it starts to connection to the gcm server (i.e. last line in the code below).

        ConnectionConfiguration config = new ConnectionConfiguration(GCM_SERVER, GCM_PORT);
        config.setSecurityMode(SecurityMode.enabled);
        config.setReconnectionAllowed(true);
        config.setRosterLoadedAtLogin(false);
        config.setSendPresence(false);
        config.setSocketFactory(SSLSocketFactory.getDefault());

        connection = new XMPPTCPConnection(config);
        connection.connect();

Am I missing something?

Thanks.

**Comment by jradcliff** [comment]
It looks like your issue is not related to this project (the [Google Ads APIs Client Library for Java](https://github.com/googleads/googleads-java-lib)). Please post this question to the [Google Cloud Messaging for Android group](https://groups.google.com/forum/#!forum/android-gcm) instead.

Thanks
