### ISSUE TITLE
How to set proxy to the ReportDownloader

### ISSUE THREAD

**Issue by lchenaction** [googleads/googleads-java-lib#43]
I don't want to set the VM/System level proxy.

So I set Axis proxy as below:

            AxisProperties.getProperties().put("proxySet", "true");
            AxisProperties.setProperty("http.proxyHost", Config.getStr(apiClient, "ProxyHost"));
            AxisProperties.setProperty("http.proxyPort", Config.getStr(apiClient, "ProxyPort"));
            AxisProperties.setProperty("https.proxyHost", Config.getStr(apiClient, "ProxyHost"));
            AxisProperties.setProperty("https.proxyPort", Config.getStr(apiClient, "ProxyPort"));

And Also I set proxy for OfficeCredentials:

        NetHttpTransport httpTransport = new NetHttpTransport.Builder().setProxy(proxy).build();
        Credential oAuth2Credential = new OfflineCredentials.Builder().forApi(OfflineCredentials.Api.ADWORDS).from(config).withHttpTransport(httpTransport).build().generateCredential();

But I have no idea how to set proxy for the ReportDownloader. Would you please enlighten me, or is there an easier way to set proxy in one place?
ReportDownloadResponse response = new ReportDownloader(adWordsSession).downloadReport(reportDefinition);

Thanks.

**Comment by jradcliff** [comment]
Thanks for pointing this out. Currently the only way to set the proxy for the ReportDownloader is [via system properties](https://github.com/googleads/googleads-java-lib#user-content-using-a-proxy). We'll look into ways to configure this programmatically.

**Comment by jradcliff** [comment]
Are you using different ClassLoaders within your application? The reason I ask is that `AxisProperties.setProperty` ultimately calls `setProperty` on [ManagedProperties](http://commons.apache.org/proper/commons-discovery/apidocs/org/apache/commons/discovery/tools/ManagedProperties.html), which simply sets the property at the _class loader_ level. Therefore, unless you are using different class loaders, this is basically equivalent to setting the system property.

**Comment by jradcliff** [comment]
I'll close this since I haven't heard back on the questions I asked back in June. Please reopen and provide more details if this is still an issue.

Thanks
