### ISSUE TITLE
Unable to submit empty urlList in SET request

### ISSUE THREAD

**Issue by mmATX** [googleads/googleads-java-lib#45]
Hey guys -
I'm trying to set a tracking template and finalURL on a keyword. I explicitly set the finalMobileUrls to null, yet when I attempt the update, I get the UrlError.MISSING_PROTOCOL for the non-existent mobile url. This is using the v201502 java client (googleads-java-lib-v1.38.0, specifically).

The code:
``` java
            Criterion keyword = new Criterion();
            keyword.setId( Long.parseLong( k.getId().getKeywordId() ) );

            BiddableAdGroupCriterion bagc = new BiddableAdGroupCriterion();
            bagc.setAdGroupId( Long.parseLong( k.getId().getAdGroupId()) );
            bagc.setCriterion( keyword );
            //If there used to be a destURL value, an empty string tells adwords to get rid of it
            bagc.setDestinationUrl("");
            bagc.setTrackingUrlTemplate(k.getTrackingTemplate()==null?"":k.getTrackingTemplate());
            if (k.getFinalURL()==null) {
            	bagc.setFinalUrls(null);
            } else {
            	bagc.setFinalUrls(new UrlList(new String[]{k.getFinalURL()}));
            }
            if (k.getFinalMobileURL()==null) {
            	bagc.setFinalMobileUrls(null);
            } else {
            	bagc.setFinalMobileUrls(new UrlList(new String[]{k.getFinalMobileURL()}));
            }
```
And the resulting soap request:
``` xml
 <soapenv:Body>
  <mutate xmlns="https://adwords.google.com/api/adwords/cm/v201502">
   <operations>
    <operator>SET</operator>
    <operand xmlns:ns2="https://adwords.google.com/api/adwords/cm/v201502" xsi:type="ns2:BiddableAdGroupCriterion">
     <adGroupId>21999324732</adGroupId>
     <criterion>
      <id>142938960012</id>
     </criterion>
     <destinationUrl/>
     <finalUrls>
      <urls>http://www.myhotel.com/chicago/promoCode={_promoCode}?kwid={_kwid}</urls>
     </finalUrls>
     <finalMobileUrls>
      <urls/>
     </finalMobileUrls>
     <trackingUrlTemplate>http://tracking.deepsearch.adlucent.com/adlucent/Redirector?kwid={_kwid}&amp;adid={creative}&amp;device={device}&amp;retailer=delventosdoodles&amp;url={lpurl}</trackingUrlTemplate>
     <urlCustomParameters>
      <parameters>
       <key>kwid</key>
       <value>217ad6637be843f3810916685e2e82c7</value>
      </parameters>
      <parameters>
       <key>promoCode</key>
       <value>chi55893</value>
      </parameters>
      <parameters>
       <key>season</key>
       <value>Fall_getaway</value>
      </parameters>
     </urlCustomParameters>
    </operand>
   </operations>
  </mutate>
 </soapenv:Body>
```
And the response:   
``` xml 
<soap:Header>
        <ResponseHeader xmlns="https://adwords.google.com/api/adwords/cm/v201502">
            <requestId>000515869d2114280ab612c5320067a4</requestId>
            <serviceName>AdGroupCriterionService</serviceName>
            <methodName>mutate</methodName>
            <operations>1</operations>
            <responseTime>101</responseTime>
        </ResponseHeader>
    </soap:Header>
    <soap:Body>
        <mutateResponse xmlns="https://adwords.google.com/api/adwords/cm/v201502">
            <rval>
                <ListReturnValue.Type>AdGroupCriterionReturnValue</ListReturnValue.Type>
                <value>
                    <AdGroupCriterion.Type>AdGroupCriterion</AdGroupCriterion.Type>
                </value>
                <partialFailureErrors xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:type="UrlError">
                    <fieldPath>operations[0].operand.finalMobileUrls.urls[0]</fieldPath>
                    <trigger/>
                    <errorString>UrlError.MISSING_PROTOCOL</errorString>
                    <ApiError.Type>UrlError</ApiError.Type>
                    <reason>MISSING_PROTOCOL</reason>
                </partialFailureErrors>
            </rval>
        </mutateResponse>
    </soap:Body>
```

I then tried every variant I could come up with of setting the urlList to null, new UrlList(new String[]), & new UrlList(null), etc & regardless of what I tried, the soap message contains the same url chunk:
``` xml
     <finalUrls>
        <urls/>
     </finalUrls>
```
& they all return UrlError.MISSING_PROTOCOL

Not surprisingly, it happens for both finalUrls and finalMobileUrls

-mm

**Comment by lchenaction** [comment]
Instead of setting null, you should set an empty list, like new UrlList(new
String[] {}), good luck!

**Comment by mmATX** [comment]
Sorry, I wasn't clear enough. I have tried:
``` java
bagc.setFinalMobileUrls(new UrlList(new String[]{}));
```
and out of desperation:
``` java
UrlList ul = new UrlList();
ul.setUrls(new String[0]);
bagc.setFinalMobileUrls(ul);
```
``` java
UrlList ul = new UrlList();
ul.setUrls(null);
bagc.setFinalMobileUrls(ul);
```
and receive UrlError.MISSING_PROTOCOL for all

**Comment by jradcliff** [comment]
Hi,

I just verified that the following approach successfully clears finalMobileUrls for a keyword:

    // Create ad group criterion with updated bid.
    Criterion criterion = new Criterion();
    criterion.setId(keywordId);

    BiddableAdGroupCriterion biddableAdGroupCriterion = new BiddableAdGroupCriterion();
    biddableAdGroupCriterion.setAdGroupId(adGroupId);
    biddableAdGroupCriterion.setCriterion(criterion);

    // Simply create a new UrlList. No need to set its urls.    
    biddableAdGroupCriterion.setFinalMobileUrls(new UrlList());

This produced the following operations XML (which succeeded):

        <mutate xmlns="https://adwords.google.com/api/adwords/cm/v201502">
            <operations>
                <operator>SET</operator>
                <operand xmlns:ns2="https://adwords.google.com/api/adwords/cm/v201502"
                        xsi:type="ns2:BiddableAdGroupCriterion">
                    <adGroupId>19067540234</adGroupId>
                    <criterion>
                        <id>10159180</id>
                    </criterion>
                    <finalMobileUrls/>
                </operand>
            </operations>
        </mutate>

Could you give that approach a try?

Thanks

**Comment by mmATX** [comment]
Yes - that is giving me the right xml. Thanks a bunch!
