### ISSUE TITLE
How to store All the results in MySQL DB ?

### ISSUE THREAD

**Issue by osingh** [googleads/googleads-java-lib#46]
I am able to get sum results from BidSimulation, But I want to store all results in my Database. Is there any way to store all results in MySQL DB.

Thanks,
Om Singh

**Comment by jradcliff** [comment]
Hi Om,

The library doesn't support this directly, but you may want to take a look at our [aw-reporting project](https://github.com/googleads/aw-reporting), which issues *report* requests using the API and then stores the report results to the datastore of your choice. You might be able to use some of the ideas there to implement a similar process for storing bid simulation results.

Thanks,
Josh, AdWords API Team

**Comment by osingh** [comment]
Hi Josh,

Thanks for reply, I will go through it. 

Thanks,
Om Singh
