### ISSUE TITLE
AdWords Axis Utility Extension

### ISSUE THREAD

**Issue by davidbotella** [googleads/googleads-java-lib#47]
Hi,

Utility hasn't been updated for months, and is still not compatible with v201502. Is there any plans to update it or shall I fork it ?

Cheers.

**Comment by jradcliff** [comment]
Hi,

I plan to update the utility within the next 2-3 weeks, so if you can wait until then, there's no need to fork the library. Sorry for the delay.

Thanks,
Josh, AdWords API Team

**Comment by jradcliff** [comment]
Hi,

[Release 2.1.0](https://github.com/googleads/googleads-java-lib/releases/tag/2.1.0) (released today) upgraded the extension utility to v201502. In addition, I updated the selector fields list for each entity to include all fields as of v201502.

Thanks
