### ISSUE TITLE
Guice version conflict with guice 4.0 project

### ISSUE THREAD

**Issue by ephe-meral** [googleads/googleads-java-lib#51]
I'm using the libraries in a playframework 2.4 project, which uses Guice 4.0.
When I try to create a new AdWordsServices object, I'm running into version related problems:

```
Caused by: java.lang.ClassNotFoundException: com.google.inject.internal.util.$ImmutableList
        at java.net.URLClassLoader.findClass(URLClassLoader.java:381) ~[na:1.8.0_45]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[na:1.8.0_45]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[na:1.8.0_45]
        ... 65 common frames omitted
```
I'm wondering what would be the best way to resolve this conflict?

**Comment by kondaurovDev** [comment]
I've got the same problem too, how can it be solved?

**Comment by jradcliff** [comment]
One way to resolve this would be to modify the ads_lib/pom.xml to include guice 4.0 dependencies. I just did this locally and it worked perfectly.

    <dependency>
      <groupId>com.google.inject</groupId>
      <artifactId>guice</artifactId>
      <version>4.0</version>
    </dependency>
    <dependency>
      <groupId>com.google.inject.extensions</groupId>
      <artifactId>guice-assistedinject</artifactId>
      <version>4.0</version>
    </dependency>
    <dependency>
      <groupId>com.google.inject.extensions</groupId>
      <artifactId>guice-multibindings</artifactId>
      <version>4.0</version>
    </dependency>

Is that a viable solution for you?

Note that we do plan on upgrading to Guice 4.0 within the library.

**Comment by jradcliff** [comment]
We upgraded to Guice 4.0 in [v2.5.0](https://github.com/googleads/googleads-java-lib/releases/tag/2.5.0). Please give that version a try and reopen this issue if you still encounter problems.

Thanks
