### ISSUE TITLE
Conflicting com.google.guava/guava versions in ads-lib release

### ISSUE THREAD

**Issue by thheller** [googleads/googleads-java-lib#54]
I'm using the `com.google.api-ads/ads-lib` artifact in a clojure project and discovered that there are 2 releases of `guava` being loaded via maven because `com.google.api-client/google-api-client` depends on `com.google.guava/guava-jdk5` instead of just `com.google.guava/guava` (like the `ads-lib`).

Not sure if `google-api-client` really needs the `jdk5` version as it seems to work fine in my project where the `19.0-rc2` version of all classes are loaded.

The extra dependency causes issues elsewhere in my project not related to `ads-lib` which I can work around by excluding the dependency but this should probably be cleaned up here.

Dependency tree (via `leiningen`) 
```
 [com.google.api-ads/ads-lib "2.5.0"]
   [com.google.api-client/google-api-client "1.20.0"]
     [com.google.guava/guava-jdk5 "13.0"]
     [com.google.oauth-client/google-oauth-client "1.20.0"]
       [com.google.code.findbugs/jsr305 "1.3.9"]
   [com.google.guava/guava "19.0-rc2"]
   [com.google.http-client/google-http-client-jackson2 "1.20.0"]
     [com.fasterxml.jackson.core/jackson-core "2.1.3"]
     [com.google.http-client/google-http-client "1.20.0"]
   [com.google.inject.extensions/guice-assistedinject "4.0"]
   [com.google.inject.extensions/guice-multibindings "4.0"]
   [com.google.inject/guice "4.0"]
     [aopalliance "1.0"]
     [javax.inject "1"]
   [commons-configuration "1.7"]
     [commons-collections "3.2.1"]
   [commons-lang "2.5"]
   [joda-time "2.8.2"]
   [net.sf.opencsv/opencsv "1.8"]
```

**Comment by christopherseeley** [comment]
Thanks for pointing this out. This is fixed in v2.6.0 which was just released.
