### ISSUE TITLE
Downloading ReportDefinitionReportType.VIDEO_PERFORMANCE_REPORT

### ISSUE THREAD

**Issue by BarakBurger** [googleads/googleads-java-lib#59]
Hi,  i am trying to download this report ReportDefinitionReportType.VIDEO_PERFORMANCE_REPORT
but something is very weird: the data is NOT being aggregated

for the same AdGroupId,CampaignId,Date i get more then one row.

and while using the ui of google ad word (website) there is only one row for this columns.

in download report data is actually split into two rows and they are equals to the actual total
but the entire calculation of all % columns are effected .

i even tried downoading a report with less column and i am getting more than one row 

could it be a bug ?

this is my code:

		Selector selector = new Selector();
		List<String> fields = selector.getFields();

		fields.add("AdGroupId");
		fields.add("CampaignId");
		fields.add("Clicks");
		fields.add("Cost");
		fields.add("Date");
		fields.add("Engagements");
		fields.add("Impressions");
		fields.add("VideoDuration");
		fields.add("VideoQuartile100Rate");
		fields.add("VideoQuartile25Rate");
		fields.add("VideoQuartile50Rate");
		fields.add("VideoQuartile75Rate");
		fields.add("VideoViews");

		DateRange dateRange = new DateRange();
		dateRange.setMin(startDate);
		dateRange.setMax(endDate);
		selector.setDateRange(dateRange);

		// Create report definition.
		ReportDefinition reportDefinition = new ReportDefinition();
		reportDefinition.setReportName("keywords convertion report #" + System.currentTimeMillis());
		reportDefinition.setDateRangeType(ReportDefinitionDateRangeType.CUSTOM_DATE);
		reportDefinition.setReportType(ReportDefinitionReportType.VIDEO_PERFORMANCE_REPORT);
		reportDefinition.setDownloadFormat(DownloadFormat.GZIPPED_CSV);
		reportDefinition.setIncludeZeroImpressions(false); // tried even delete this row but didnt change
		reportDefinition.setSelector(selector);

		// try {
		// download the report
		ReportDownloader reportDownloader = new ReportDownloader(adWordsSession);
		reportDownloader.setReportDownloadTimeout(HTTP_READ_TIMEOUT);
		ReportDownloadResponse response = reportDownloader.downloadReport(reportDefinition);
                GZIPInputStream inputStream = new GZIPInputStream(response.getInputStream());

**Comment by jradcliff** [comment]
Hi,

This issues list is for issues specifically with the Java client library. For general issues/questions with the AdWords API, please post to the AdWords API group instead.

https://groups.google.com/forum/#!forum/adwords-api

Thanks,
Josh, AdWords API Team

**Comment by BarakBurger** [comment]
this question is for java api - i wrote a code in java and download the results - the result from the java code are incorrect and to prove it  checked with the API my issue is for java reasults

**Comment by jradcliff** [comment]
Hi,

Sorry - what I meant was that your question is about the behavior of the AdWords API and is not specific to which client library you are using.

Either way, I think the issue here is that the VIDEO_PERFORMANCE_REPORT is implicitly broken out by [CreativeId](https://developers.google.com/adwords/api/docs/appendix/reports/video-performance-report#creativeid). I recommend adding that field to your report -- if you see distinct values once you take that field into consideration, then that will confirm my theory.

Thanks

**Comment by BarakBurger** [comment]
Thank you for your help :+1:
