### ISSUE TITLE
Can't run the example: dfp.axis.v201511.lineitemservice.CreateVideoLineItems - Always return an error

### ISSUE THREAD

**Issue by rguimaraesr** [googleads/googleads-java-lib#61]
Can't run the example: **dfp.axis.v201511.lineitemservice.CreateVideoLineItems** - Always return an error

I'm always getting the error below:

**[FeatureError.MISSING_FEATURE @ lineItem[0]; trigger:'VAS_CONTENT_HIERARCHY']**

can someone help me? I'm using a Small Bussiness Account. @jradcliff

**Comment by rguimaraesr** [comment]
@jradcliff

**Comment by Raneves** [comment]
this error is caused by type of DFP Small Business. This segmentation `targeting.setContentTargeting(contentTargeting);` is avaiable only for Premium users.
For segmentation in Small Business you needs create a CustomTargeting with key-values:
```
//Custom Target Key Value
	    CustomCriteria customCriteria = new CustomCriteria();
	    customCriteria.setKeyId(targetingKey.getId());
	    customCriteria.setOperator(CustomCriteriaComparisonOperator.IS);
	    customCriteria.setValueIds(new long[] {targetingValue.getId()});
	    
	    //CustomTarget
	    CustomCriteriaSet customCriteriaSet = new CustomCriteriaSet();
	    customCriteriaSet.setLogicalOperator(CustomCriteriaSetLogicalOperator.OR);
	    customCriteriaSet.setChildren(new CustomCriteriaNode[] {customCriteria });
Targeting targeting = new Targeting();
	    targeting.setCustomTargeting(customCriteriaSet);

**Comment by christopherseeley** [comment]
Raneves is correct, this example depends on certain premium video features being enabled.
