### ISSUE TITLE
There's some API to set a campaign with SkipAd?

### ISSUE THREAD

**Issue by rguimaraesr** [googleads/googleads-java-lib#62]
@christopherseeley  I didn't find any documentation about set a campaign with SkipAd. This exists or it's a closed API feature?

**Comment by jradcliff** [comment]
Since this is not specific to the Java client library, could you post this question to the [DFP API forum](https://groups.google.com/forum/#!forum/google-doubleclick-for-publishers-api) instead?

Thanks,
Josh, Ads API Team
