### ISSUE TITLE
Upgrade of Utility

### ISSUE THREAD

**Issue by davidbotella** [googleads/googleads-java-lib#63]
Hi !
Do you plan to maintain the Utility with new version of the library and API ? It only works with v201506 right now for the 2.8 version on maven.

Regards,
David B.

**Comment by jradcliff** [comment]
Hi David,

Could you let me know which features of the utility you use? For example, are you using it to work with *all* entity types, or just a subset?

Thanks,
Josh, AdWords API Team

**Comment by jradcliff** [comment]
Hi David,

Could your provide the info I requested in my previous update?

Thanks,
Josh, AdWords API Team

**Comment by davidbotella** [comment]
Hi,
I use it for a subset of main entities : campaigns, adgroups, ads, keywords. The main task seems to update the SelectorFields.java. Delegates doesn't need to be updated. Is it something that could be done from a XML file describing all the fields ? (WSDL) Is it something available online ?

**Comment by jswaf** [comment]
Hello,
I also use this adwords-axis-utility-extension 2.4.0 which supports AdWords API v201506. As all we know the sunset date of v201506 is coming next month, I am really anxious that I cannot access AdWords until new utility which supports at least v201509 hopefully v201601 comes.
I use these classes:
com.google.api.ads.adwords.axis.utility.extension.delegates.AbstractGetMutateDelegate
com.google.api.ads.adwords.axis.utility.extension.delegates.AdGroupAdDelegate
com.google.api.ads.adwords.axis.utility.extension.delegates.AdGroupBidModifierDelegate
com.google.api.ads.adwords.axis.utility.extension.delegates.AdGroupCriterionDelegate
com.google.api.ads.adwords.axis.utility.extension.delegates.AdGroupDelegate
com.google.api.ads.adwords.axis.utility.extension.delegates.AdGroupFeedDelegate
com.google.api.ads.adwords.axis.utility.extension.delegates.BudgetDelegate
com.google.api.ads.adwords.axis.utility.extension.delegates.CampaignAdExtensionDelegate
com.google.api.ads.adwords.axis.utility.extension.delegates.CampaignCriterionDelegate
com.google.api.ads.adwords.axis.utility.extension.delegates.CampaignDelegate
com.google.api.ads.adwords.axis.utility.extension.delegates.CampaignFeedDelegate
com.google.api.ads.adwords.axis.utility.extension.delegates.CustomerSyncDelegate
com.google.api.ads.adwords.axis.utility.extension.delegates.FeedDelegate
com.google.api.ads.adwords.axis.utility.extension.delegates.FeedItemDelegate
com.google.api.ads.adwords.axis.utility.extension.delegates.FeedMappingDelegate
com.google.api.ads.adwords.axis.utility.extension.delegates.GeoLocationDelegate
com.google.api.ads.adwords.axis.utility.extension.util.ListUtil
com.google.api.ads.adwords.axis.utility.extension.util.SelectorFields
com.google.api.ads.adwords.axis.utility.extension.util.SelectorFields.FieldType
com.google.api.ads.adwords.axis.utility.extension.util.SelectorFields.getFields

Will the new version of this utility ship soon?

Thanks,
Wataru

**Comment by jradcliff** [comment]
Thanks for providing your usage details, David and Wataru. Given that this sounds like a critical extension for you both, I'll look into upgrading it to v201601 before [the sunset of v201506](https://developers.google.com/adwords/api/docs/sunset-dates#api-versions).

Cheers,
Josh, AdWords API Team

**Comment by jswaf** [comment]
Thank you very much for giving us a good news of upgrading!
I am really looking forward to being released.

Best Wishes,
Wataru

**Comment by jradcliff** [comment]
Good news! I just released [version 2.12.0](https://github.com/googleads/googleads-java-lib/releases/tag/2.12.0), which includes an upgrade of the extension utility to v201603. This is the latest version of the AdWords API and was released yesterday:

http://googleadsdeveloper.blogspot.com/2016/03/announcing-v201603-of-adwords-api.html

Cheers,
Josh, AdWords API Team

**Comment by jswaf** [comment]
I appreciate it that this library which supports the latest AdWords API v201603 is now available!

Regards,
Wataru

**Comment by jradcliff** [comment]
Hi David, Wataru,

After careful consideration, we have decided to **deprecate** the [AdWords Axis Utility Extension](https://github.com/googleads/googleads-java-lib/tree/master/modules/adwords_axis_utility_extension). The extension will continue to be available and functional until the sunset of AdWords API v201603 (currently *estimated* to occur in [October 2016](http://googleadsdeveloper.blogspot.com/2016/01/new-release-schedule-for-adwords-api.html)). However, we will no longer upgrade the extension for new versions of the AdWords API.

Ahead of the deprecation date, please update your application to use the [standard Java client library](https://github.com/googleads/googleads-java-lib). If instead you would prefer to continue to use the extension, you are free to do so, but you will have to make the necessary changes for each AdWords API release within your own copy of the module.

Thank you,
Josh, AdWords API Team

**Comment by jswaf** [comment]
Hello Josh,

Thank you for your announcing. It is kind of shocking news, since I depends on the utility significantly. I guess I have to remake my code and it's a big deal.

Well, anyway, your information is a great help to me in making my future development plan.

Regards,
Wataru

**Comment by jradcliff** [comment]
Hi Wataru,

Feel free to reach out to the AdWords API Team via our forum if you have any questions about the migration.

https://groups.google.com/forum/#!forum/adwords-api

We're here to help!

Cheers,
Josh, AdWords API Team
