### ISSUE TITLE
INTERNAL_API_ERROR in EstimateKeywordTraffic.java

### ISSUE THREAD

**Issue by vipeeshbyt** [googleads/googleads-java-lib#65]
InternalApiError.UNEXPECTED_INTERNAL_API_ERROR @ com.google.ads.api.services.common.error.InternalApiError in EstimateKeywordTraffic.java

**Comment by jradcliff** [comment]
Since this is not specific to the client library, could you instead post your issue to the AdWords API forum?

https://groups.google.com/forum/#!forum/adwords-api

Please include more details there as well, e.g., the request you are issuing (with sensitive information such as your developer token removed) so we can investigate.

Thanks,
Josh, AdWords API Team

**Comment by vipeeshbyt** [comment]
Hi,
I tried to post my response in google adword api forum.But i was not able to see my post in forum.Please find below the response and help me to resolve the issue.
<?xml version="1.0" encoding="UTF-8"?><soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">    <soapenv:Header>        <ns1:RequestHeader xmlns:ns1="https://adwords.google.com/api/adwords/o/v201509" soapenv:mustUnderstand="0">            <ns2:clientCustomerId xmlns:ns2="https://adwords.google.com/api/adwords/cm/v201509">***-***-*****</ns2:clientCustomerId>            <ns3:developerToken xmlns:ns3="https://adwords.google.com/api/adwords/cm/v201509">*******_********</ns3:developerToken>            <ns4:userAgent xmlns:ns4="https://adwords.google.com/api/adwords/cm/v201509">Mozilla/5.0 (Linux; Android 4.3; Nexus 10 Build/JSS15Q) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/42.0.2307.2 Safari/537.36 (AwApi-Java, AdWords-Axis/2.8.0, Common-Java/2.8.0, Axis/1.4, Java/1.7.0_80, maven)</ns4:userAgent>            <ns5:validateOnly xmlns:ns5="https://adwords.google.com/api/adwords/cm/v201509">false</ns5:validateOnly>            <ns6:partialFailure xmlns:ns6="https://adwords.google.com/api/adwords/cm/v201509">false</ns6:partialFailure>        </ns1:RequestHeader>    </soapenv:Header>    <soapenv:Body>        <get xmlns="https://adwords.google.com/api/adwords/o/v201509">            <selector>                <campaignEstimateRequests>                    <adGroupEstimateRequests>                        <keywordEstimateRequests>                            <keyword>                                <ns7:text xmlns:ns7="https://adwords.google.com/api/adwords/cm/v201509">Restaurants in Bangalore</ns7:text>                                <ns8:matchType xmlns:ns8="https://adwords.google.com/api/adwords/cm/v201509">EXACT</ns8:matchType>                            </keyword>                        </keywordEstimateRequests>                        <keywordEstimateRequests>                            <keyword>                                <ns9:text xmlns:ns9="https://adwords.google.com/api/adwords/cm/v201509">Bangalore Restaurants</ns9:text>                                <ns10:matchType xmlns:ns10="https://adwords.google.com/api/adwords/cm/v201509">EXACT</ns10:matchType>                            </keyword>                        </keywordEstimateRequests>                        <keywordEstimateRequests>                            <keyword>                                <ns11:text xmlns:ns11="https://adwords.google.com/api/adwords/cm/v201509">Booking Restaurants in bangalore</ns11:text>                                <ns12:matchType xmlns:ns12="https://adwords.google.com/api/adwords/cm/v201509">EXACT</ns12:matchType>                            </keyword>                        </keywordEstimateRequests>                        <maxCpc>                            <ns13:microAmount xmlns:ns13="https://adwords.google.com/api/adwords/cm/v201509">100</ns13:microAmount>                        </maxCpc>                    </adGroupEstimateRequests>                    <criteria xmlns:ns14="https://adwords.google.com/api/adwords/cm/v201509" xsi:type="ns14:Location">                        <ns14:id>1007768</ns14:id>                    </criteria>                    <criteria xmlns:ns15="https://adwords.google.com/api/adwords/cm/v201509" xsi:type="ns15:Language">                        <ns15:id>1000</ns15:id>                    </criteria>                    <dailyBudget>                        <ns16:microAmount xmlns:ns16="https://adwords.google.com/api/adwords/cm/v201509">100</ns16:microAmount>                    </dailyBudget>                </campaignEstimateRequests>            </selector>        </get>    </soapenv:Body></soapenv:Envelope>
[WARN ] [com.google.api.ads.adwords.lib.client.AdWordsServiceClient.soapXmlLogger]  SOAP Response:<?xml version="1.0" encoding="UTF-8"?><soap:Envelope xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/">    <soap:Header>        <ResponseHeader xmlns:ns2="https://adwords.google.com/api/adwords/cm/v201509" xmlns="https://adwords.google.com/api/adwords/o/v201509">            <ns2:requestId>00052c41b7e127e00a4cad02f601f041</ns2:requestId>            <ns2:serviceName>LocationCriterionService</ns2:serviceName>            <ns2:methodName>get</ns2:methodName>            <ns2:operations>1</ns2:operations>            <ns2:responseTime>155</ns2:responseTime>        </ResponseHeader>    </soap:Header>    <soap:Body>        <soap:Fault>            <faultcode>soap:Server</faultcode>            <faultstring>[InternalApiError.UNEXPECTED_INTERNAL_API_ERROR @ com.google.ads.api.services.common.error.InternalApiError.&lt;init&gt;(InternalApiErro]</faultstring>            <detail>                <ApiExceptionFault xmlns="https://adwords.google.com/api/adwords/o/v201509" xmlns:ns2="https://adwords.google.com/api/adwords/cm/v201509">                    <ns2:message>[InternalApiError.UNEXPECTED_INTERNAL_API_ERROR @ com.google.ads.api.services.common.error.InternalApiError.&lt;init&gt;(InternalApiErro]</ns2:message>                    <ns2:ApplicationException.Type>ApiException</ns2:ApplicationException.Type>                    <ns2:errors xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:type="ns2:InternalApiError">                        <ns2:fieldPath/>                        <ns2:trigger/>                        <ns2:errorString>InternalApiError.UNEXPECTED_INTERNAL_API_ERROR</ns2:errorString>                        <ns2:ApiError.Type>InternalApiError</ns2:ApiError.Type>                        <ns2:reason>UNEXPECTED_INTERNAL_API_ERROR</ns2:reason>                    </ns2:errors>                </ApiExceptionFault>            </detail>        </soap:Fault>    </soap:Body></soap:Envelope>

**Comment by jradcliff** [comment]
Hi,

The forum is moderated, so the first time you post there you won't see your message until someone approves your membership. Since I now see your posts on the forum, let's continue the discussion there.

Thanks
