### ISSUE TITLE
DCM sample is missing

### ISSUE THREAD

**Issue by karthickomd** [googleads/googleads-java-lib#67]
Hi Team,

DFA 6 Java sample folder is removed from this path around OCT14.

We are looking for DCM samples, working on Data transfer & match table project.

if DCM samples can't be added here, please re-direct me to right person who can help me further.

Highly appreciate your help.

Regards,
Karthick K
OMD Dubai

**Comment by jimper** [comment]
The DFA SOAP API was shut down back in Sept 2015. Our newer API is REST based and uses the [Google APIs client library for Java](https://developers.google.com/api-client-library/java/). You can find sample code linked from the [developer documentation](https://developers.google.com/doubleclick-advertisers/), however we do not offer any samples related to DT or MT files, which are not served from the DCM API. You should contact your account manager or the DCM support team for more info about those.

**Comment by jradcliff** [comment]
Closing per jimper@'s previous comment.
