### ISSUE TITLE
AdWordsServices could not be initialized NoClassDefFoundError

### ISSUE THREAD

**Issue by artemMcNevan** [googleads/googleads-java-lib#68]
Hi there) I have such issue like here: https://github.com/googleads/googleads-java-lib/issues/55

Here full stack trace and details:
http://stackoverflow.com/questions/35935831/referenced-libraries-are-missing-and-classdefnotfound-error

I thought the reason is referenced libraries are missing...but it's not so
My web app works locally but doesn't work at the server...
I'm using GAE(google web application eclipse project) and not using maven...I need to solve this issue for GAE, I added all dependent libs(Guice 4.0, Guice assisted inject 4.0, Guice multibindings 4.0) and  exception are still thrown...Plz help me

**Comment by jradcliff** [comment]
Hi,

I think we're already discussing this one on the AdWords API Forum here:

https://groups.google.com/d/msg/adwords-api/7uicwqvyatY/edRzB2z3IQAJ

Please see my last response and suggestion there.

Thanks,
Josh, AdWords API Team

**Comment by jradcliff** [comment]
Hi,

I'll close this issue since, per your latest post on the forum, this issue is now resolved.

Thanks,
Josh, AdWords API Team
