### ISSUE TITLE
Can not get the Value of a creative template Variable

### ISSUE THREAD

**Issue by xcuben** [googleads/googleads-java-lib#69]
Hi everybody,

with  ((TemplateCreative)creative).getCreativeTemplateVariableValues(i).getUniqueName();
i can get the Name of the Variable but I would like to get the Value of this Variable . 
Is it Possible ? 

Best
O.N

**Comment by jradcliff** [comment]
Hi O.N,

You can get the value, but you'll need to cast it to the proper subclass of `BaseCreativeTemplateVariableValue` first, e.g.,

```java
BaseCreativeTemplateVariableValue baseVariableValue = 
  ((TemplateCreative) creative).getCreativeTemplateVariableValues(i);

// If the value is a String...
StringCreativeTemplateVariableValue stringVariableValue = 
  (StringCreativeTemplateVariableValue) baseVariableValue;

// Get the value.
String variableValue = stringVariableValue.getValue();
```

Cheers,
Josh, AdWords API Team

**Comment by xcuben** [comment]
perfect . works like a charm , thanks a lot
