### ISSUE TITLE
Pause Products Within Existing Product Campaign

### ISSUE THREAD

**Issue by applecrusher** [googleads/googleads-java-lib#71]
Is there a way to pause an existing product within a Product Campaign(More specifically a Product Group)? I think it would require a Product Partition, but all the examples showing adding new Product Partition, and I would like to modify an existing Campaign. I am not familiar with the API that well, although I have been reading for several hours without any answer to my question. I appreciate your time. Thank you.

**Comment by jradcliff** [comment]
Hi,

You're in luck :) - the wiki page for the product partition utility covers this use case:

https://github.com/googleads/googleads-java-lib/wiki/Shopping-product-partition-utility-for-AdWords#exclude-a-node-from-bidding

Basically, you can convert your ProductPartition node from a `BiddableAdGroupCriterion` to a `NegativeAdGroupCriterion` to exclude that node from bidding.

I'll close this issue, but if you have further questions feel free to reopen it.

Also, if you have AdWords API questions that are not specific to the Java client library, please post them to the [AdWords API Forum](https://groups.google.com/forum/#!forum/adwords-api).

Cheers,
Josh, AdWords API Team
