### ISSUE TITLE
Can not get the value of master_companion_creative_id

### ISSUE THREAD

**Issue by xcuben** [googleads/googleads-java-lib#72]
Hi Guys,

I would like to make a report with all creatives with 

- size in (970x250,800x250)
- creativeId != master_companion_creative_id

in my code , i did the following : 
`// Create a statement to only select image creatives.
	        StatementBuilder statementBuilder = new StatementBuilder()
	            .where("size IN ('970x250','800x250') AND id !=XXXXXX ")
	            .orderBy("id ASC")`
but i just can not find what should i do to get the  master_companion_creative_id 

thanks for response.
xcuben

**Comment by christopherseeley** [comment]
You can use the CreativeSetService to get the IDs of all the master and companion creatives. This example shows how to use the service:
https://github.com/googleads/googleads-java-lib/blob/2.11.0/examples/dfp_axis/src/main/java/dfp/axis/v201602/creativesetservice/GetAllCreativeSets.java

For usage questions not specific to java please post in our [product forum](https://groups.google.com/forum/#!msg/google-doubleclick-for-publishers-api/) going forward - it'll get more visibility and possibly help others with similar issues.
