### ISSUE TITLE
Export function for Creative-Template ?

### ISSUE THREAD

**Issue by xcuben** [googleads/googleads-java-lib#74]
Hi guys,

Is there any possibility to export/import a creative remplate within DFP Axis ? 

Bests
Xcuben

**Comment by christopherseeley** [comment]
You can export/retrieve creative templates, but not import/create. The service is read only. There's an example for getting all creative templates here:
https://github.com/googleads/googleads-java-lib/blob/master/examples/dfp_axis/src/main/java/dfp/axis/v201602/creativetemplateservice/GetAllCreativeTemplates.java

**Comment by xcuben** [comment]
Hi christopherseeley
 Thanks for the Resonse.
By export/import creativeTemplate i meant the export / import Buttons that i have in the adServer (See image buttons (1) and (2) ). By clicking on export you get a JSON file with all informations/fields..etc of the creativeTemplate. By the same way, clicking Import allows you to import a JSON file in the AdServer.
And i was just wondering if there is any possibility to do the same thing in the API with AXIS.

Here an example of how would the JSON looks like: 

**{**
  **"name":** "SAMPLE NAME OF THE CREATIVE TEMPLATE",
  **"description":** "DESCRIPTION",
 "variables": [ 
   some variables...etc
   ],
  "formatter": 
}

Bests
