### ISSUE TITLE
Export/import Functions in DFP API?

### ISSUE THREAD

**Issue by xcuben** [googleads/googleads-java-lib#75]
Hi

 By clicking on export you get a JSON file with all informations/fields..etc of the creativeTemplate. By the same way, clicking Import allows you to import a JSON file in the AdServer.
And i was just wondering if there is any possibility to do the same thing in the API with AXIS.

![creativetemplateexportimport](https://cloud.githubusercontent.com/assets/13620662/14344359/6a079806-fca7-11e5-9aaf-4fc07c7e930e.png)

Here an example of how would the JSON looks like: 

**{**
  **"name":** "SAMPLE NAME OF THE CREATIVE TEMPLATE",
  **"description":** "DESCRIPTION",
 "variables": [ 
   some variables...etc
   ],
  "formatter": 
}

Bests

**Comment by christopherseeley** [comment]
The JSON export isn't available in the SOAP API, but the data you can retrieve in the API is the same. You can transform the data into valid JSON for import.

**Comment by xcuben** [comment]
OK  I see.
And how exactly can I import the JSON via the API. I tried to take a look in the repos but I didnt find anything.

**Comment by christopherseeley** [comment]
There's no way of creating CreativeTemplates via the API, so there's currently no way to achieve the import functionality.
