### ISSUE TITLE
Google's Gson Conversion not Compatible with "Money" Object

### ISSUE THREAD

**Issue by applecrusher** [googleads/googleads-java-lib#76]
I am trying to convert the campaign objects to JSON using GSON. However, it seems that the Money Object is not compatible with this and I figured since GSON was Google's JSON conversion/serializer tool that this would be relevant and something to fix if it is simple. Below is the error that I get. Please let me know if this is something you will consider fixing or will not.

Exception in thread "main" java.lang.IllegalArgumentException: class com.google.api.ads.adwords.axis.v201603.cm.Money declares multiple JSON fields named __equalsCalc

**Comment by jradcliff** [comment]
Hi,

The `Money` class is generated from the service WSDLs, so we do not modify that class. However, you could work around this by using an
[ExclusionStrategy](http://static.javadoc.io/com.google.code.gson/gson/2.6.2/com/google/gson/ExclusionStrategy.html) as follows:

```java
    @Test
    public void testMoney() throws Exception {
      // Create an ExclusionStrategy that will exclude the __equalsCalc and __hashCode
      // fields from the ComparableValue superclass.
      ExclusionStrategy strategy = new ExclusionStrategy(){
        @Override
        public boolean shouldSkipField(FieldAttributes f) {
          if (ComparableValue.class.equals(f.getDeclaringClass())) {
            if ("__equalsCalc".equals(f.getName()) ||
                "__hashCodeCalc".equals(f.getName())) {
              return true;
            }
          }
          return false;
        }
      
        @Override
        public boolean shouldSkipClass(Class<?> clazz) {
          return false;
        }
      };

      Gson gson = new GsonBuilder().
          setExclusionStrategies(strategy)
          .create();
      
      Money money = new Money(null, 25000000L);
      String json = gson.toJson(money);
      
      Money moneyFromJson = gson.fromJson(json, Money.class);
      assertEquals(money, moneyFromJson);
    }
```

Cheers,
Josh, AdWords API Team
