### ISSUE TITLE
Mobile search volume.

### ISSUE THREAD

**Issue by iamtrk** [googleads/googleads-java-lib#79]
Hi,
   How to get Mobile search volume. I have followed the GetKeywordIdeas example in Optimization directory, but it's currently reporting total search volume. How can I limit it to mobile search volume?

Thanks,
Ravi.

**Comment by jradcliff** [comment]
Hi Ravi,

Since this is more of a question on how to use the AdWords API, could you post it to the AdWords API Forum instead?

https://groups.google.com/forum/#!forum/adwords-api

Thanks,
Josh, AdWords API Team
