### ISSUE TITLE
AdWords reports downloaded as XML files aren't valid XML files.

### ISSUE THREAD

**Issue by glukasz** [googleads/googleads-java-lib#81]
The following characters shouldn't be present in XML documents: <, &, >, ", '. Those characters should be replaced with &lt;, &amp;, &gt;, &quot;, and &apos;. However AdWords API (Java) doesn't perform the replacement, the xml files contain invalid character which cause the XML parser to fail.

**Comment by jradcliff** [comment]
Hi,

This is by design. The report service is meant to return raw, unescaped data, so the XML format comes back as a standard XML document.

Thanks,
Josh, AdWords API Team

**Comment by simpleAndrew** [comment]
I think author meant that XML reserved characters must be escaped according to standard:
https://www.w3.org/TR/xml/#syntax
So, it seems that &, >, < must be escaped or you'll end up producing invalid XML document

**Comment by jradcliff** [comment]
Ah, I see. If that's the case, could the original author post an example of a response that is malformed on the AdWords API forum?

https://groups.google.com/forum/#!forum/adwords-api

That's a better spot for general API issues. This github issues list is for issues specific to the Java client library.

Thanks,
Josh, AdWords API Team
