### ISSUE TITLE
Adding UpdateText Ad Examples

### ISSUE THREAD

**Issue by applecrusher** [googleads/googleads-java-lib#83]
I am looking in the examples folder and I do not see any example to update a ad or any text ad. I do not know if this was done on purpose or much more difficult than it seems. I tried running code I thought would work for the ad and the status will update, however the headline is not updated from the textAd. How can this be achieved and would it be possible to add an example of this to the folder? The below is the code I have leaving out my details: 

```
            Long adGroupId = 0L; //ad group id
		    Long id =  0L; //keyword id
			AdGroupAd textAdGroupAd;
			AdWordsSession session;
			AdWordsServices adWordsServices;
			Operator operator = null;
			TextAd textAd = new TextAd();
			textAd.setId(id);
			    
			textAd.setHeadline("MY NEW HEADLINE");
			    

			textAdGroupAd = new AdGroupAd();
			textAdGroupAd.setAdGroupId(adGroupId); 
			    
			textAdGroupAd.setStatus(AdGroupAdStatus.ENABLED);
	
	        operator = Operator.SET;
			adWordsServices = new AdWordsServices();
			session = null //session

			textAdGroupAd.setAd(textAd);
				
			AdGroupAdServiceInterface adGroupAdService =
					        adWordsServices.get(session, AdGroupAdServiceInterface.class);
				
				
			AdGroupAdOperation textAdGroupAdOperation = new AdGroupAdOperation();
			textAdGroupAdOperation.setOperand(textAdGroupAd);
			textAdGroupAdOperation.setOperator(operator);
				
			AdGroupAdOperation[] operations =
			            new AdGroupAdOperation[] {textAdGroupAdOperation};

			// Add ads.
			try {
			     AdGroupAdReturnValue result = adGroupAdService.mutate(operations);
			     System.out.println(toStringFromAdwordsObject(result)); //custom method to print adwords objects
				} catch (ApiException e) {
					e.printStackTrace();
				} catch (RemoteException e) {
					e.printStackTrace();
				}
```

**Comment by jradcliff** [comment]
Hi,

TextAds are *immutable*, so if you want to make a change to one, you should:

1.  Add a new TextAd with the desired changes -- see [AddTextAds example](https://github.com/googleads/googleads-java-lib/blob/master/examples/adwords_axis/src/main/java/adwords/axis/v201603/basicoperations/AddTextAds.java).
2.  Remove or pause the existing TextAd -- see [RemoveAd example](https://github.com/googleads/googleads-java-lib/blob/master/examples/adwords_axis/src/main/java/adwords/axis/v201603/basicoperations/RemoveAd.java).

Thanks,
Josh, AdWords API Team
