### ISSUE TITLE
DFP 

### ISSUE THREAD

**Issue by arishvarunmishra** [googleads/googleads-java-lib#84]
I watched https://www.youtube.com/watch?v=iJP3dvuNhPg but does not found the related files so can you provide the sample shown in this video

**Comment by christopherseeley** [comment]
The slide deck and code examples used are available under the March 2015 workshops section here:
https://sites.google.com/site/displayadsworkshops/slides-and-links

**Comment by arishvarunmishra** [comment]
Thanks for you Quick response and kind support

On Thu, May 12, 2016 at 6:23 PM, Chris Seeley <notifications@github.com>
wrote:

> Closed #84 <https://github.com/googleads/googleads-java-lib/issues/84>.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/googleads/googleads-java-lib/issues/84#event-658537314>
>



-- 


*Thanks & RegardsVarun Mishra *

*Co No. :+919999191660*

*skype id: vvarun.mishra*
