### ISSUE TITLE
Problem sending data to report download server for Keywords Performance Report

### ISSUE THREAD

**Issue by kahing** [googleads/googleads-java-lib#87]
I am consistently getting ReportException: Problem sending data to report download server/SocketTimeoutException for this query on one of the accounts:

SELECT Date, AccountDescriptiveName, Criteria, AdNetworkType1, Status, CampaignName, AdGroupName, SystemServingStatus, KeywordMatchType, Id, Labels, CpcBid, Cost, Impressions, Clicks, AveragePosition, CrossDeviceConversions, ViewThroughConversions, FirstPageCpc, TopOfPageCpc, FirstPositionCpc, QualityScore, ClickAssistedConversions, ImpressionAssistedConversions, SearchImpressionShare, SearchRankLostImpressionShare, SearchExactMatchImpressionShare FROM KEYWORDS_PERFORMANCE_REPORT DURING 20160417,20160517

Also tried querying for last 2 weeks or 1 week with the same result. Up'ing the timeout via `reportDownloader.setReportDownloadTimeout` to 10 minutes and it would timeout after 10 minutes.

Any idea why?

**Comment by jradcliff** [comment]
Hi,

Since this is not specific to the Java client library, could you post this issue to the AdWords API Forum instead?

https://groups.google.com/forum/#!forum/adwords-api

Thanks,
Josh, AdWords API Team

**Comment by kahing** [comment]
Just found the forum and posted there, sorry about that!
