### ISSUE TITLE
Library looking for google-ads-api-java-build.properties file

### ISSUE THREAD

**Issue by davidbotella** [googleads/googleads-java-lib#90]
Hi,

Does this debug message is something important ? Looks like it's looking after another properties file instead of "ads.properties". I'm debugging a case after updgrading to v201607 and it appeared in the logs. It stops when renaming the ads.properties to google-ads-api-java-build.properties.

```
DEBUG 2016-08-04 10:19:54,052 [main][ConfigurationHelper.java:156] : Did not load optional configuration google-ads-api-java-build.properties:
com.google.api.ads.common.lib.conf.ConfigurationLoadException: Encountered a problem reading the provided configuration file "google-ads-api-java-build.properties"!
```

Thanks,

**Comment by jradcliff** [comment]
Hi,

You can ignore that log message, since it only occurs if a given configuration file is optional.

However, I can see why this could be alarming. I'll take a look to see a) why the config file is not found and b) if we can make the log message clarify that this is not critical.

Thanks,
Josh, AdWords API Team

**Comment by Olof-n** [comment]
The DEBUG errors that it spits out is really annoying. How can I turn the logger off or decrease the level?

**Comment by jradcliff** [comment]
Hi,

The log message is going to the log named:

`com.google.api.ads.common.lib.utils.logging.AdsServiceLoggers.ads_api_lib`

If you set that log's level to `INFO` or higher in your log configuration, then those messages will not appear.

Thanks,
Josh, AdWords API Team

**Comment by jradcliff** [comment]
Hi,

I made a few changes in `v3.2.0` to address this. Please check out the **Common** section of the [release notes](https://github.com/googleads/googleads-java-lib/releases/tag/3.2.0) for details.

Thanks,
Josh, AdWords API Team
