### ISSUE TITLE
AddProductPartitionTree Sample code not working

### ISSUE THREAD

**Issue by vishalthakur48** [googleads/googleads-java-lib#92]
Hi Team,

I am trying to run the AddProductPartitionTree Sample code but it is failing with the following Exception:

faultDetail: 
	{https://adwords.google.com/api/adwords/cm/v201605}ApiExceptionFault:<message>[CriterionError.INVALID_PRODUCT_BIDDING_CATEGORY @ operations[8].operand.criterion.caseValue; trigger:'ProductBiddingCategory{type=BIDDING_CATEGORY_L1, value=ProductCategoryId: -5914235892932915235}']</message><ApplicationException.Type>ApiException</ApplicationException.Type><errors xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:type="CriterionError"><fieldPath>operations[8].operand.criterion.caseValue</fieldPath><trigger>ProductBiddingCategory{type=BIDDING_CATEGORY_L1, value=ProductCategoryId: -5914235892932915235}</trigger><errorString>CriterionError.INVALID_PRODUCT_BIDDING_CATEGORY</errorString><ApiError.Type>CriterionError</ApiError.Type><reason>INVALID_PRODUCT_BIDDING_CATEGORY</reason></errors>

[CriterionError.INVALID_PRODUCT_BIDDING_CATEGORY @ operations[8].operand.criterion.caseValue; trigger:'ProductBiddingCategory{type=BIDDING_CATEGORY_L1, value=ProductCategoryId: -5914235892932915235}']

**Comment by jradcliff** [comment]
Hi,

Hmmm...that's odd. I just ran that example and it succeeded for me. Did you change anything in the example?

I also verified that ID `-5914235892932915235` is still an `ACTIVE` category:

            <rval>
                <ConstantData.Type>ProductBiddingCategoryData</ConstantData.Type>
                <dimensionValue>
                    <ProductDimension.Type>ProductBiddingCategory</ProductDimension.Type>
                    <type>BIDDING_CATEGORY_L2</type>
                    <value>-1806041116650009580</value>
                </dimensionValue>
                <parentDimensionValue>
                    <ProductDimension.Type>ProductBiddingCategory</ProductDimension.Type>
                    <type>BIDDING_CATEGORY_L1</type>
                    <value>-5914235892932915235</value>
                </parentDimensionValue>
                <country>US</country>
                <status>ACTIVE</status>
                <displayValue>
                    <key>en</key>
                    <value>Diaper Bags</value>
                </displayValue>
            </rval>

Which country is your campaign targeting? Perhaps that's not a valid ID for that country. You can check this by looking for it in the output from [GetProductCategoryTaxonomy](https://github.com/googleads/googleads-java-lib/blob/master/examples/adwords_axis/src/main/java/adwords/axis/v201605/shoppingcampaigns/GetProductCategoryTaxonomy.java).

Thanks,
Josh, AdWords API Team

**Comment by vishalthakur48** [comment]
Hi Josh,

Sorry for the late reply. 
My Campaign is targeting India and that seems to be the issue.
However I was able to download the ids for the following countries
"US", "GB", "DE", "FR", "JP", "AU", "NL", "IT", "BR", "SE", "NO", "TR".
Not sure what code I have to use to get the ids for India.

**Comment by jradcliff** [comment]
Hi Vishal,

The country code for India would be `IN`.

Thanks,
Josh Radcliff, AdWords API Team

**Comment by vishalthakur48** [comment]
Hi Josh,

I tried GetProductCategoryTaxonomy  sample code using country code as IN and the result is null.

 Selector selector = new SelectorBuilder()
      .equals(ConstantDataField.Country, "IN")
      .build();
It works for other country code but not for IN.

Thanks
Vishal

**Comment by jradcliff** [comment]
Hi Vishal,

Since this is a general API issue and not specific to the Java library, could you post your question to the AdWords API Forum instead?

https://groups.google.com/forum/#!forum/adwords-api

Thanks,
Josh, AdWords API Team
