### ISSUE TITLE
Service creation takes takes too long on appengine.

### ISSUE THREAD

**Issue by vivekimsit** [googleads/googleads-java-lib#94]
Hi,

I have the following line of code snippet:

`LineItemServiceInterface s = new DfpServices().get(session, LineItemServiceInterface.class);`

The above line works fine on my local machine but on uploading to the AppEngine it takes around ~14sec to execute, it seems weird but what could be the reason behind it and how to solve this issue?

Thanks,

**Comment by christopherseeley** [comment]
Is this happening on the AppEngine devserver too, or only when it's deployed?

**Comment by christopherseeley** [comment]
Closing since no one else is experiencing this issue. If you're impacted please reopen.

**Comment by vivekimsit** [comment]
Well I am really surprised since you verified this issue yourself. I don't know how many people are using this API but yes I am totally blocked on this, in fact I was expecting some fix in the latest version.

**Comment by christopherseeley** [comment]
I pinned the latency down to the instantiation of the jax-ws service, outside of this library's code. As a workaround, you can use the [App Engine Java Flexible Environment](https://cloud.google.com/appengine/docs/flexible/java/). Testing there showed much lower latency.
