### ISSUE TITLE
2.19 AdwordsSessionBuilder CharMatcher.ascii() no such method

### ISSUE THREAD

**Issue by jayhahn** [googleads/googleads-java-lib#95]
Using the latest build of this library throws this error. We rollbacked to 2.18 for now.

```
java.lang.NoSuchMethodError: com.google.common.base.CharMatcher.ascii()Lcom/google/common/base/CharMatcher;
        at com.google.api.ads.adwords.lib.client.AdWordsSession$Builder.validate(AdWordsSession.java:518)
        at com.google.api.ads.adwords.lib.client.AdWordsSession$Builder.build(AdWordsSession.java:476)

```

And here is the code in AdwordsSession class that is causing the issue. 

```

      // Check that user agent is not empty or the default.
      if (Strings.isNullOrEmpty(userAgent)
          || userAgent.contains(DEFAULT_USER_AGENT)) {
        this.userAgent = UNKNOWN_USER_AGENT;
      } else if (!CharMatcher.ascii().matchesAllOf(userAgent)) {
        throw new ValidationException(
            String.format("User agent [%s] contains non-ASCII characters.", userAgent),
            "userAgent");
      }
```

**Comment by jradcliff** [comment]
Hi,

Could you check which version of Guava you have on your classpath? The `ascii` method was added in [Guava 19.0](https://google.github.io/guava/releases/19.0/api/docs/com/google/common/base/CharMatcher.html#ascii()).

Thanks,
Josh, AdWords API Team

**Comment by jayhahn** [comment]
Ah Guava is set at 17.0. Will upgrade that.

**Comment by jradcliff** [comment]
I'll mark this closed, but feel free to reopen it if you encounter issues after upgrading your Guava dependencies.

Cheers,
Josh, AdWords API Team
