### ISSUE TITLE
Add entry type parameter to Page

### ISSUE THREAD

**Issue by markus-s24** [googleads/googleads-java-lib#96]
For type safety it would be nice, if the type of page entries is defined at Page, e.g. Page<E>. This would allow to handle different page subclasses the same way without losing type safety.

**Comment by jradcliff** [comment]
Hi,

Could you clarify which ads API you're referring to (DFP or AdWords)? Also, if you have a specific subclass/example that illustrates the issue, that would be helpful.

Thanks,
Josh, AdWords API Team

**Comment by markus-s24** [comment]
Hi Josh,

I am referring to AdWords. Example: 

AdGroupAdPage should be like:
public class AdGroupAdPage extends Page<AdGroupAd>...

Page should be like:
public class Page<E> {
   public abstract E[] getEntries();
   public abstract E getEntries(int i);
   public abstract void setEntries(E[] entries);
   public abstract void setEntries(int i, E entry);
   ...
}

This way one can write code to iterate over pages of different page types in a type safe way. I did not check whether all pages implement the getEntries/setEntries methods. If not all pages do that, an intermediate abstract class could be added for those who do.

**Comment by jradcliff** [comment]
Hi,

Thanks for clarifying. Unfortunately, the `Page` class and its subclasses are generated via `wsimport` (JAX-WS) and `wsdl2java` (Axis), so we don't have complete control over them. However, I'll take a look to see if there's a way to customize the generator.

Cheers,
Josh, AdWords API Team

**Comment by markus-s24** [comment]
A new interface that is implemented by the concrete subclasses only would be fine too. That way even classes that do not inherit from Page can be handled too.

**Comment by jradcliff** [comment]
Hi,

Thanks for the suggestion. The WSDL -> code generator tools generate classes that mirror the objects in the WSDL, so in the `AdGroupAdPage` example, the generated classes reflect the type definitions for [AdGroupAdPage](https://developers.google.com/adwords/api/docs/reference/v201607/AdGroupAdService.AdGroupAdPage) and the [Page](https://developers.google.com/adwords/api/docs/reference/latest/AdGroupAdService.Page) base class, which only has a `totalNumEntries` attribute.

That being said, there may be a way for us to post-process the generated classes to make them easier to work with. I'll have to look into that and get back to you.

Thanks,
Josh, AdWords API Team

**Comment by markus-s24** [comment]
Hi Josh,

thanks a lot for caring about this issue.

Markus

**Comment by yeison** [comment]
I'd like to request the same feature for DFP Pages.  It would be really great if all of the Page types in DFP inherited from a common Page Interface.  It would greatly reduce the amount of duplicated code in my application.

**Comment by christopherseeley** [comment]
Fixed in v3.3.0
