### ISSUE TITLE
Feature request: BatchJobManager

### ISSUE THREAD

**Issue by markus-s24** [googleads/googleads-java-lib#97]
Like Bing Ads has a BulkServiceManager for its BulkService encapsulating all the details about its usage, I would like to have this for the BatchJobService. This should handle upload, polling, download and parsing the result to entities in one method providing a future with the result.

**Comment by jradcliff** [comment]
Hi,

Thanks for the feedback. We took a slightly different approach from what you described with the [BatchJobHelper utility](https://github.com/googleads/googleads-java-lib/wiki/BatchJobHelper-utility-for-AdWords). The utility provides core functionality for uploading operations and downloading results. For polling, different users may have different strategies (including their own rate-limit handlers for the `BatchJobService.get` call), so we wanted to leave the polling step up to the user's discretion.

As a general approach, the client library utilities avoid making changes to a user's account, but instead provide a convenient mechanism for users to get the operations that they would then pass on to `mutate` (or `get`) requests. This is the approach used in the [Shopping Product Partition utility](https://github.com/googleads/googleads-java-lib/wiki/Shopping-product-partition-utility-for-AdWords) as well, which generates operations for the user, but allows the user the flexibility to submit those operations as he sees fit.

Thanks,
Josh, AdWords API Team

**Comment by markus-s24** [comment]
Hi Josh,

we are currently using the BatchJobHelper utility and it leaves very much implementation effort to the user. So we are still preferring the "normal" API even for batches of operations. When looking at the Bing Ads solution, it removes the need for any generic code. What I want is something like this dummy interface:

    Future<List<OperationResult>> mutate(List<Operation> operations)

This allows for executing operations with just one method call. Any configurability regarding polling strategies could be configured with a custom strategy, if needed. Else there should be a reasonable default.

For creating operations I currently need no helper utility, because our software works on entity level, e.g. first synchronizes/creates all accounts, then the campaigns etc.

**Comment by jradcliff** [comment]
Hi,

Sorry, I know it's been quite a while since we discussed this issue, and I'm guessing you implemented your own solution long ago. Could you let me know if this is still an enhancement you would find useful and would integrate into your application?

Thanks,
Josh, AdWords API Team

**Comment by markus-s24** [comment]
Hi Josh,

yes, of course. Our current implementation is a bit complex and sometimes not all operations always terminate with success and I don't know why. Maybe our timeout is too short. So we are currently using it just for less important "fire and forget" labelling and pause/unpause operations.

If you provide a reliable and easy to use implementation, we would additionally change our more important api calls to this new solution. This would reduce the number of requests we are executing, because the "normal" api calls have entity limits. So we currently need to do batching.

Thanks,
Markus

**Comment by christopherseeley** [comment]
AdWords API has been turned down and replaced by the Google Ads API. Closing as stale.
