### ISSUE TITLE
Feature request: Implement ApiError.toString()

### ISSUE THREAD

**Issue by markus-s24** [googleads/googleads-java-lib#98]
Provide a meaningful message including the main details of the error in ApiError.toString() for each subclass of ApiError. This allows to see the root of the problem in stack traces.

**Comment by jradcliff** [comment]
Hi,

This is an interesting idea -- I'll look into this along with [your Paging suggestion](https://github.com/googleads/googleads-java-lib/issues/96), since both would involve post-processing the source files generated by `wsimport` and `wsdl2java`.

Thanks,
Josh, AdWords API Team

**Comment by christopherseeley** [comment]
Fixed in v3.3.0
