### ISSUE TITLE
Update Example for v201607 - examples/adwords_axis/src/main/java/adwords/axis/v201607/reporting/DownloadCriteriaReport.java

### ISSUE THREAD

**Issue by applecrusher** [googleads/googleads-java-lib#99]
Starting on line 87 you have:

    ReportingConfiguration reportingConfiguration =
        new ReportingConfiguration.Builder()
            .skipReportHeader(false)
            .skipColumnHeader(false)
            .skipReportSummary(false)
            // Enable to allow rows with zero impressions to show.
            .includeZeroImpressions(false)
            .build();

But skipColumnHeader is no longer valid and zero impressions has been removed since v201605 because it should be included in the HTTP header:

https://developers.google.com/adwords/api/docs/reference/#v201605

Also, how do I include zero impressions in the http headers via this java api? Thank you.

**Comment by jradcliff** [comment]
Hi,

The `ReportingConfiguration` object will automatically set the HTTP header for `includeZeroImpressions` based on that attribute of the same name, so you should use that attribute to include zero impressions for both AWQL and ReportDefinition-based requests.

Regarding `skipColumnHeader`, that is still supported -- could you point me to where you are seeing that it is *not* supported, or provide a response from a request that failed?

Thanks,
Josh, AdWords API Team

**Comment by applecrusher** [comment]
In my attempt to update I accidentally added older jars. Sorry about that. Thank you for your response.
